### PR TITLE
Fix multi item

### PR DESCRIPTION
**Pull request by Leits**
Вирішення проблеми з відсутністю даних про item у кеші tender_ownera при видалення предмету закупівлі.

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/167)

### CODE REVIEW

**Comment by mykhaly** [comment]
*[op_robot_tests/tests_files/multiItemTender.robot, line 46 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFnE0l_z9K3d4C3J5vj:-KFnE0l_z9K3d4C3J5vk:729587049) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/multiItemTender.robot#L46)):*
навіщо тут tender_owner?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/167)*

**Comment by mykhaly** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/167)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 46 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFnE0l_z9K3d4C3J5vj:-KFoJ8_SEsgKFZHvLdyC:837452685) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/multiItemTender.robot#L46)):*
І нащо ж? :)

---

*[op_robot_tests/tests_files/service_keywords.py, line 334 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFoJdPvFi0BRtJzU2n2:-KFoJdPvFi0BRtJzU2n3:-1552210332) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/service_keywords.py#L334)):*
@Leits, можеш пояснити, що це дає?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/167)*

**Comment by selurvedu** [comment]
@mykhaly, you're doing it wrong. Щоб Треба було зробити merge цього PR в devel і потім пушнути merge commit і в devel, і в master (щоб в devel було "This branch is even with master"). Тепер треба знову робити merge devel'у в master.

**Comment by mykhaly** [comment]
Sorry :(

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 46 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFnE0l_z9K3d4C3J5vj:-KFrzmrk6ciQ7v3Amh71:1520614967) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/multiItemTender.robot#L46)):*
Бо для операції із цим предметом нам потрібно мати у кеші його id, який лежить у description.

---

*[op_robot_tests/tests_files/service_keywords.py, line 334 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFoJdPvFi0BRtJzU2n2:-KFrzXWs7GZSihW-JQVU:1080177144) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/service_keywords.py#L334)):*
Якщо у obj немає ключа 'title', воно поверне ’’.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/167)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 46 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFnE0l_z9K3d4C3J5vj:-KFyVEW1tABliLqKYVQy:676269983) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/multiItemTender.robot#L46)):*
:+1:

---

*[op_robot_tests/tests_files/service_keywords.py, line 334 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/167#-KFoJdPvFi0BRtJzU2n2:-KFyVJYBARy3rirfb_oR:1633763894) ([raw file](https://github.com/openprocurement/robot_tests/blob/4d07281c44190e4332d38b71f8108e4abb6fc038/op_robot_tests/tests_files/service_keywords.py#L334)):*
А, бо id в тайтлі, ясно.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/167)*

**Pull request merged**
