### PR TITLE
Work with cache on keywords level

### PR DESCRIPTION
**Pull request by Leits**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/108)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 289 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/108#-KD7lpnubWj0GFeg9DL0:-KD7lpnubWj0GFeg9DL1:1143779279) ([raw file](https://github.com/openprocurement/robot_tests/blob/bab40975bb19079cfbd230093ec45266f78f1df8/op_robot_tests/tests_files/keywords.robot#L289)):*
Чому тут не забрав `set_to_object`?

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 78 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/108#-KD7ldz15RSooFtrxwLz:-KD7ldz15RSooFtrxwM-:1980023798) ([raw file](https://github.com/openprocurement/robot_tests/blob/bab40975bb19079cfbd230093ec45266f78f1df8/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L78)):*
А чому цей блок видаляємо?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/108)*

**Comment by selurvedu** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 78 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/108#-KD7ldz15RSooFtrxwLz:-KD87yqCGBWSqI0Fm5CG:67252369) ([raw file](https://github.com/openprocurement/robot_tests/blob/bab40975bb19079cfbd230093ec45266f78f1df8/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L78)):*
А, дійшло. Винесли на рівень вище же.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/108)*

**Comment by Leits** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 289 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/108#-KD7lpnubWj0GFeg9DL0:-KDN572ldyPfUvWQWw_U:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/bab40975bb19079cfbd230093ec45266f78f1df8/op_robot_tests/tests_files/keywords.robot#L289)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/108)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/108#-:-KDVxxsAlOzzW7Nw3dcT:1417088721)*

**Pull request merged**
