### PR TITLE
Add possibility to create lots in awards

### PR DESCRIPTION
**Pull request by Krokop**
Додав можливість створювати awards з лотами

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/299)

### CODE REVIEW

**Comment by selurvedu** [comment]
В загальному все добре, бо зміни дуже маленькі, але хотілося б почути думку +@mykhaly.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KS09Me39PTA_I7dCiU-:-KS09Me42THZScPrvD9s:b-em71ml) ([raw file](https://github.com/openprocurement/robot_tests/blob/ffb5f4ddd25eec0217903dd633eb5dd35138d4c9/op_robot_tests/tests_files/keywords.robot#L261)):*
> ```RobotFramework
> 
> Підготувати дані про постачальника
>   [Arguments]  ${username}  ${lotIndex}={-1}
> ```

Має бути `${-1}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-:-KS09i5sJk0GaBSAlzoW:b-fmd910)*

**Comment by Krokop** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KS09Me39PTA_I7dCiU-:-KS0XjOqjda4n88BmgbX:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/ffb5f4ddd25eec0217903dd633eb5dd35138d4c9/op_robot_tests/tests_files/keywords.robot#L261)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Має бути `${-1}`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-:-KS2ErWzQbhWTfFYStMI:bnfp4nl)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[op_robot_tests/tests_files/initial_data.py, line 141 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHA92Vrhtz1zY9bS8P:-KSHA92WhWs-hWgp4mo4:b-q1971z) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/initial_data.py#L141)):*
> ```Python
>     del data["tenderPeriod"]
>     for lot in data.get('lots', []):
>         del lot['minimalStep']
> ```

Чисто теоретично в лоті може не бути поля **minimalStep**. Тому краще було б тут зробити отак:
```
lot.pop('minimalStep', None)
```

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KSHCzwsxDPAWrJaGpCo:b-riu2ok) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
> ```RobotFramework
> 
> Підготувати дані про постачальника
>   [Arguments]  ${username}  ${lotIndex}=${-1}
> ```

Отут **`${lotIndex}`**  буде типу `string`, а не `int`, якщо він буде переданий в ківорд ззовні.
Тому не знаю, яким чином зараз працює порівняння в наступному **`Run keyword if`**.
Вихід з ситуації - 
```
${lotIndex}=  Convert To Number  ${lotIndex}
```

---

*[op_robot_tests/tests_files/keywords.robot, line 263 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHDS8eQlbwfeO2oaIx:-KSHDS8goDBnYt9ozF6y:b-1915qc) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L263)):*
> ```RobotFramework
>   [Arguments]  ${username}  ${lotIndex}=${-1}
>   ${supplier_data}=  test_supplier_data
>   Run Keyword If  ${lotIndex} > -1  Set To Dictionary  ${supplier_data.data}  lotID=${USERS.users['${username}'].tender_data.data['lots'][${lotIndex}]['id']}
> ```

Якщо **`${username}`** буде грати не **Quinta**, то поля **`${USERS.users['${username}'].tender_data.data['lots'][${lotIndex}]['id']}`** не буде.
Тому айдішку лота потрібно діставати з **`${USERS.users['${tender_owner}'].initial_data.data['lots'][${lotIndex}]['id']}`**.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by Krokop** [comment]
*[op_robot_tests/tests_files/initial_data.py, line 141 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHA92Vrhtz1zY9bS8P:-KSHMU2LGZ3GdnXVX6MH:bb6un1j) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/initial_data.py#L141)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Чисто теоретично в лоті може не бути поля **minimalStep**. Тому краще було б тут зробити отак:
> ```
> lot.pop('minimalStep', None)
> ```
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by Krokop** [comment]
*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KSHMl2-4RPHSjIpSF5J:bb6un1j) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Отут **`${lotIndex}`**  буде типу `string`, а не `int`, якщо він буде переданий в ківорд ззовні.
> Тому не знаю, яким чином зараз працює порівняння в наступному **`Run keyword if`**.
> Вихід з ситуації - 
> ```
> ${lotIndex}=  Convert To Number  ${lotIndex}
> ```
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by Krokop** [comment]
*[op_robot_tests/tests_files/keywords.robot, line 263 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHDS8eQlbwfeO2oaIx:-KSHMuhXRshZtOuITcWe:bb6un1j) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L263)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Якщо **`${username}`** буде грати не **Quinta**, то поля **`${USERS.users['${username}'].tender_data.data['lots'][${lotIndex}]['id']}`** не буде.
> Тому айдішку лота потрібно діставати з **`${USERS.users['${tender_owner}'].initial_data.data['lots'][${lotIndex}]['id']}`**.
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KSVwwez2O0GGuyoIt4y:bux12m1) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
<details><summary><i>Previously, Krokop (Oleg Serbokryl) wrote…</i></summary>
> Done
</details>
@mykhaly, ні, `${-1}` дає int. Я ж недарма на цей самий рядок писав коментар.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by Krokop** [comment]
*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KSXtYN3K91jHrtEzBNC:b-jc5hx2) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> @mykhaly, ні, `${-1}` дає int. Я ж недарма на цей самий рядок писав коментар.
</details>
То мені повернути як було?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KSaI4do1uZfE1Vp8USw:b-yjro04) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
>якщо він буде переданий в ківорд ззовні.

@selurvedu: аргумент, переданий [звідси](https://github.com/openprocurement/robot_tests/blob/ffb5f4ddd25eec0217903dd633eb5dd35138d4c9/op_robot_tests/tests_files/base_keywords.robot#L958), не буде int'ом:

@krokop: Ні.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 261 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/299#-KSHCzwr3KNudhttrTYf:-KU6odod8Fh4I4cx1KdF:bsr1ev1) ([raw file](https://github.com/openprocurement/robot_tests/blob/65306651536009946799f2733fb53f57a2e4cc3c/op_robot_tests/tests_files/keywords.robot#L261)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> >якщо він буде переданий в ківорд ззовні.
> 
> @selurvedu: аргумент, переданий [звідси](https://github.com/openprocurement/robot_tests/blob/ffb5f4ddd25eec0217903dd633eb5dd35138d4c9/op_robot_tests/tests_files/base_keywords.robot#L958), не буде int'ом:
> 
> @krokop: Ні.
</details>
@mykhaly, дійсно, не буде int'ом, але, на жаль, порівняння в `Run Keyword If` успішно пройде. Я вже не раз згадував про те, що eval'у в Robot Framework більше, ніж хотілося б. Демонструю:

numbers.py
```python
gen_my_float = lambda: 12290015898.07
gen_my_float_as_str = lambda: str(gen_my_float())
gen_minus_one = lambda: -1
```

numbers.robot
```robotframework
*** Settings ***
Library  numbers.py

*** Test Cases ***
Comparison Of Values With Known Types
  ${my_float}=  gen_my_float
  Log  ${my_float}
  ${my_float_as_str}=  gen_my_float_as_str
  Log  ${my_float_as_str}
  Should Be Equal  ${my_float}  ${my_float_as_str}

Comparison Of Int And Inline Value
  ${minus_one}=  gen_minus_one
  Should Be Equal  -1  ${minus_one}

Comparison Of Int And Inline Value With Implicit Evaluation
  ${minus_one}=  gen_minus_one
  ${result}  Set Variable If  -1 == ${minus_one}  True  False
  Should Be True  ${result}
  Should Be True  ${result}

Another Comparison With Implicit Evaluation
  ${minus_one}=  gen_minus_one
  Should Be True  -1 == ${minus_one}
```

Результат виконання:
```
==============================================================================
Comparison Of Values With Known Types                                 | FAIL |
12290015898.1 (float) != 12290015898.1 (string)
------------------------------------------------------------------------------
Comparison Of Int And Inline Value                                    | FAIL |
-1 (string) != -1 (integer)
------------------------------------------------------------------------------
Comparison Of Int And Inline Value With Implicit Evaluation           | PASS |
------------------------------------------------------------------------------
Another Comparison With Implicit Evaluation                           | PASS |
------------------------------------------------------------------------------
```

Аналогічно з іншими флоутами і інтами – -1, 0, 3.14 і так далі.
Перші два ламаються, як і очікується, а інші два, на жаль, проходять. Я не перевіряв всі ківорди, які містять перевірку умови (`Should *`, `* If`), але бачу таку закономірність:
eval є не там, де keyword порівнює два значення між собою чи перевіряє їх типи, а саме там, де keyword має просто отримати `True` або `False` на місці одного з аргументів.
Іншими словами, перевірка `>`, `<`, `==` і т.п. здійснюється не ківордом безпосередньо, а саме черз eval, який і видає `True` або `False`, і вже на цей результат дивиться ківорд.

Повертаючись до нашого коду: все правильно, `Convert To Number`потрібен завжди, коли число береться з вхідних даних (аргументів) і не потрібен тоді, коли число створюється прямо в ківорді, а не береться ззовні.

P.S. Отаких шматочків коду – перевірок на eval'и і інші неочевидні речі в Robot Framework, всякі там corner cases – в мене ціла купа, можна починати вести збірник граблів, які варто обходити.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/299)*

**Pull request merged**
