### PR TITLE
Rename test cases and edit tags

### PR DESCRIPTION
**Pull request by annawzz**
Rename `tender` to `lot` in test cases, add critical levels to tests, edit tags in scenarios.

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/343)

### CODE REVIEW

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/343#-:-KV4mQv1k8QCA4rY2B3r:bnfp4nl)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 142 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/343#-KVN0Ah64hT9zEvdJ_Bu:-KVN0Ah64hT9zEvdJ_Bv:b-t9xl4l) ([raw file](https://github.com/openprocurement/robot_tests/blob/9a42c68817d5390442b43b4ba31e0f5bd7b2b082/op_robot_tests/tests_files/openProcedure.robot#L142)):*
> ```RobotFramework
>   ...      viewer
>   ...      ${USERS.users['${viewer}'].broker}
>   ...      tender_view_criteria  level2
> ```

FYI: цього тега немає в аргумент файлах.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/343)*

**Comment by kosaniak** [comment]
*[op_robot_tests/tests_files/openProcedure.robot, line 142 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/343#-KVN0Ah64hT9zEvdJ_Bu:-KVPZxPuxy9s73mAVJX6:b-xwnttc) ([raw file](https://github.com/openprocurement/robot_tests/blob/9a42c68817d5390442b43b4ba31e0f5bd7b2b082/op_robot_tests/tests_files/openProcedure.robot#L142)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> FYI: цього тега немає в аргумент файлах.
</details>
Є https://github.com/openprocurement/robot_tests/blob/eauction-2.4.x/robot_tests_arguments/dgf_financial.txt#L17, ми включали його лише у dgf_financial , бо стосується тільки фінансової процедури

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/343)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 142 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/343#-KVN0Ah64hT9zEvdJ_Bu:-KVa1BpnZ7fSntOE723d:b32w0x) ([raw file](https://github.com/openprocurement/robot_tests/blob/9a42c68817d5390442b43b4ba31e0f5bd7b2b082/op_robot_tests/tests_files/openProcedure.robot#L142)):*
<details><summary><i>Previously, kosaniak wrote…</i></summary>
> Є https://github.com/openprocurement/robot_tests/blob/eauction-2.4.x/robot_tests_arguments/dgf_financial.txt#L17, ми включали його лише у dgf_financial , бо стосується тільки фінансової процедури
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/343)*

**Pull request merged**
