### PR TITLE
Modify qualifications and contracting

### PR DESCRIPTION
**Pull request by annawzz**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/334)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 2 of 2 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[op_robot_tests/tests_files/contract_signing.robot, line 29 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURpAq58QoYXNRQC-Cq:-KURpAq6XB-S92tRDT1b:bv8osk2) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/contract_signing.robot#L29)):*
> ```RobotFramework
>   ...      tender_owner
>   ...      ${USERS.users['${tender_owner}'].broker}
>   ...      tender_view_exclude
> ```

Хай буде тег `complaint_period` замість цього.

---

*[op_robot_tests/tests_files/contract_signing.robot, line 38 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURpGGFgZv-wv8p9dtc:-KURpGGGMySFWT4aFRfh:btep088) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/contract_signing.robot#L38)):*
> ```RobotFramework
>   ...      tender_owner
>   ...      ${USERS.users['${tender_owner}'].broker}
>   ...      contract_sign_exclude
> ```

Хай буде `stand_still` замість цього.

---

*[op_robot_tests/tests_files/keywords.robot, line 788 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURcynwIz3IOnBRWU0w:-KURcynxdLoIvS5v3l3O:b-6onp79) ([raw file](https://github.com/openprocurement/robot_tests/blob/6a9532e5a8210625aa84fa93fa52607dd8b5bb90/op_robot_tests/tests_files/keywords.robot#L788)):*
> ```RobotFramework
> 
> 
> Дочекатись дати початку періоду кваліфікацій
> ```

`кваліфікацій` → `кваліфікації`

---

*[op_robot_tests/tests_files/keywords.robot, line 405 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURfUi9ASPJPDbnTL2X:-KURfUiAvKwQWnEbOac0:b9br5bj) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/keywords.robot#L405)):*
> ```RobotFramework
>   ${match_in_document}=  Set Variable  False
>   :FOR  ${document_index}  IN RANGE  ${number_of_documents}
>   \  ${field_value}=  Отримати дані із тендера  ${username}  ${tender_uaid}  bids[${bid_index}].documents[${document_index}].${field}
> ```

Доведеться зробити це більш високорівнево – додати ківорд з такою сигнатурою:
```
Отримати дані із документу пропозиції
  [Arguments]  ${username}  ${tender_uaid}  ${bid_index}  ${document_index}  ${field}
  ...
  [Return]  знайдене_значення
```

---

*[op_robot_tests/tests_files/qualification.robot, line 27 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURd547lRQquWs88tyq:-KURd547lRQquWs88tyr:b-42x3q3) ([raw file](https://github.com/openprocurement/robot_tests/blob/6a9532e5a8210625aa84fa93fa52607dd8b5bb90/op_robot_tests/tests_files/qualification.robot#L27)):*
> ```RobotFramework
> 
> 
> Можливість дочекатись дати початку кваліфікацій
> ```

Тут так само.

---

*[op_robot_tests/tests_files/qualification.robot, line 233 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURebMEILRTuYvvfQds:-KURebMEILRTuYvvfQdt:bg6egtv) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L233)):*
> ```RobotFramework
> 
> Можливість завантажити протокол аукціону в пропозицію кандидата
>   [Tags]   ${USERS.users['${provider}'].broker}: Подання пропозиції
> ```

Поки що хай буде `Процес кваліфікації`.

---

*[op_robot_tests/tests_files/qualification.robot, line 236 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURe7ipOEvhaKbQxsTb:-KURe7iqLtlp68rDX5N1:bifzrs1) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L236)):*
> ```RobotFramework
>   ...  provider
>   ...  ${USERS.users['${provider}'].broker}
>   ...  add_auction_protocol_to_bid_by_provider_for_qualification
> ```

Якщо викинути `_by_provider`, то смисл не втратиться, тому викинь.

І нехай qualification буде префіксом.

---

*[op_robot_tests/tests_files/qualification.robot, line 271 at r7](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUS1p-bPyBXaMBiO6Hr:-KUS1p-cdpCoHwW1HtDc:b-m74ec6) ([raw file](https://github.com/openprocurement/robot_tests/blob/80996c043872f317eda20bc93d01cf81df459fca/op_robot_tests/tests_files/qualification.robot#L271)):*
> ```RobotFramework
>   ...  qualification_add_doc_to_first_award  level3
>   ${file_path}  ${file_name}  ${file_content}=  create_fake_doc
>   Run As  ${tender_owner}  Завантажити документ з причинами дискваліфікації постачальника  ${file_path}  ${TENDER['TENDER_UAID']}  0
> ```

Поміняй на виклик `Завантажити документ рішення кваліфікаційної комісії`.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 81 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURgVE73hyUa70x4qh8:-KURgVE73hyUa70x4qh9:bqm7ym8) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L81)):*
> ```RobotFramework
>   ${tender}=  set_access_key  ${tender}  ${USERS.users['${username}'].access_token}
>   ${response}=  Call Method  ${USERS.users['${username}'].client}  upload_bid_document  ${filepath}  ${tender}  ${bid_id}  documents
>   ${document} =  Create Dictionary  filepath=${filepath}  upload_response=${response}
> ```

`} =` → `}=`
І зайвий рівень вкладеності, можна обійтись без `${document}` починаючи з цього рядка і нижче, вистачить самого `${response}`. Конкретно:
Цей рядок викинути і зробити нижче заміну `${document['upload_response']` → `${response`.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 703 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURna5WoD_aNUZX3Z-0:-KURna5XcFYJV5-6yR6U:bvc0re2) ([raw file](https://github.com/openprocurement/robot_tests/blob/4b39ee173a9b3a352a77ef86b0f1ec7cd6fd4faf/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L703)):*
> ```RobotFramework
>   ${tender}=  openprocurement_client.Пошук тендера по ідентифікатору  ${username}  ${tender_uaid}
>   ${title}=  Set Variable  Disqualified
>   ${award}=  Run Keyword If  '${tender.data.awards[${award_num}].suppliers[0].identifier.id}' == '${tender.data.awards[0].suppliers[0].identifier.id}'
> ```

Придумай, що робити, якщо умова не виконалась. Наприклад,
```robotframework
...  ELSE  Fail  Ідентифікатори учасників у пропозиції 0 і ${award_num} не співпадають
```

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 842 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURq8vPUoxJ7SF1Op8Q:-KURq8vQbEF00qC9IVWQ:b8y3s45) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L842)):*
> ```RobotFramework
>   ${tender}=  set_access_key  ${tender}  ${USERS.users['${username}'].access_token}
>   ${response}=  Call Method  ${USERS.users['${username}'].client}  upload_contract_document  ${filepath}  ${tender}  ${contract_id}  documents
>   ${document} =  Create Dictionary  filepath=${filepath}  upload_response=${response}
> ```

Тут все так само, як в `Завантажити протокол аукціону`.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 670 at r7](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUS1xedX0UhliKiRYGU:-KUS1xeeOEMb_AN2ns5k:bg2dxsn) ([raw file](https://github.com/openprocurement/robot_tests/blob/80996c043872f317eda20bc93d01cf81df459fca/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L670)):*
> ```RobotFramework
> 
> 
> Завантажити документ з причинами дискваліфікації постачальника
> ```

Весь цей ківорд тепер дублює попередній, тому можна його сміливо викинути.

---

*[robot_tests_arguments/dgf_financial.txt, line 54 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURqe4mx-RjmtTGF_pW:-KURqe4n4S89XLKOWMgg:b-oyjknk) ([raw file](https://github.com/openprocurement/robot_tests/blob/a6fca543093fef1db3a25434b9521077d54813aa/robot_tests_arguments/dgf_financial.txt#L54)):*
> ```
> -i qualification
> -i qualification_add_doc_to_first_award
> -i add_auction_protocol_to_bid_by_provider_for_qualification
> ```

Не забудь замінити тег.

---

*[robot_tests_arguments/dgf_other.txt, line 51 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURrKkDuCDOKWL5BWPV:-KURrKkEHYm9aTMN3M6k:b-w6oidt) ([raw file](https://github.com/openprocurement/robot_tests/blob/a6fca543093fef1db3a25434b9521077d54813aa/robot_tests_arguments/dgf_other.txt#L51)):*
> ```
> -i qualification
> -i qualification_add_doc_to_first_award
> -i add_auction_protocol_to_bid_by_provider_for_qualification
> ```

Тут теж.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Comment by annawzz** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[op_robot_tests/tests_files/contract_signing.robot, line 29 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURpAq58QoYXNRQC-Cq:-KUSJ5UmhkdseBjRQTlQ:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/contract_signing.robot#L29)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Хай буде тег `complaint_period` замість цього.
</details>
Done.

---

*[op_robot_tests/tests_files/contract_signing.robot, line 38 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURpGGFgZv-wv8p9dtc:-KUSJ68A8UlN-crP4EdL:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/contract_signing.robot#L38)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Хай буде `stand_still` замість цього.
</details>
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 788 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURcynwIz3IOnBRWU0w:-KUS_X1i5lJDRyUX7l27:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/6a9532e5a8210625aa84fa93fa52607dd8b5bb90/op_robot_tests/tests_files/keywords.robot#L788)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> `кваліфікацій` → `кваліфікації`
</details>
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 405 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURfUi9ASPJPDbnTL2X:-KUSbed_MGN190WPrIoA:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/keywords.robot#L405)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Доведеться зробити це більш високорівнево – додати ківорд з такою сигнатурою:
> ```
> Отримати дані із документу пропозиції
>   [Arguments]  ${username}  ${tender_uaid}  ${bid_index}  ${document_index}  ${field}
>   ...
>   [Return]  знайдене_значення
> ```
</details>
Done.

---

*[op_robot_tests/tests_files/qualification.robot, line 27 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURd547lRQquWs88tyq:-KUS_YigglbZFGaeW92Q:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/6a9532e5a8210625aa84fa93fa52607dd8b5bb90/op_robot_tests/tests_files/qualification.robot#L27)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Тут так само.
</details>
Done.

---

*[op_robot_tests/tests_files/qualification.robot, line 233 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURebMEILRTuYvvfQds:-KUS_cazXu3eTu3PGT6J:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L233)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Поки що хай буде `Процес кваліфікації`.
</details>
Done.

---

*[op_robot_tests/tests_files/qualification.robot, line 236 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURe7ipOEvhaKbQxsTb:-KUS_xLWgnkVetS4XGyP:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L236)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Якщо викинути `_by_provider`, то смисл не втратиться, тому викинь.
> 
> І нехай qualification буде префіксом.
</details>
Done.

---

*[op_robot_tests/tests_files/qualification.robot, line 271 at r7](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUS1p-bPyBXaMBiO6Hr:-KUSa4rXLGnIFm34Lap-:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/80996c043872f317eda20bc93d01cf81df459fca/op_robot_tests/tests_files/qualification.robot#L271)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Поміняй на виклик `Завантажити документ рішення кваліфікаційної комісії`.
</details>
Done.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 81 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURgVE73hyUa70x4qh8:-KUSdBI9A5K5djEC0Cc-:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L81)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> `} =` → `}=`
> І зайвий рівень вкладеності, можна обійтись без `${document}` починаючи з цього рядка і нижче, вистачить самого `${response}`. Конкретно:
> Цей рядок викинути і зробити нижче заміну `${document['upload_response']` → `${response`.
</details>
Done.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 703 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURna5WoD_aNUZX3Z-0:-KUSanFZJl3XWYj4HONC:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/4b39ee173a9b3a352a77ef86b0f1ec7cd6fd4faf/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L703)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Придумай, що робити, якщо умова не виконалась. Наприклад,
> ```robotframework
> ...  ELSE  Fail  Ідентифікатори учасників у пропозиції 0 і ${award_num} не співпадають
> ```
</details>
Done.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 670 at r7](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUS1xedX0UhliKiRYGU:-KUSaNGmYC404TeD9rQg:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/80996c043872f317eda20bc93d01cf81df459fca/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L670)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Весь цей ківорд тепер дублює попередній, тому можна його сміливо викинути.
</details>
Done.

---

*[robot_tests_arguments/dgf_financial.txt, line 54 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURqe4mx-RjmtTGF_pW:-KUSap1Pv4x4PN3XDP9t:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/a6fca543093fef1db3a25434b9521077d54813aa/robot_tests_arguments/dgf_financial.txt#L54)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Не забудь замінити тег.
</details>
Done.

---

*[robot_tests_arguments/dgf_other.txt, line 51 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURrKkDuCDOKWL5BWPV:-KUSapiNuq4PbbsrScE3:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/a6fca543093fef1db3a25434b9521077d54813aa/robot_tests_arguments/dgf_other.txt#L51)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Тут теж.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Comment by annawzz** [comment]
Review status: 0 of 11 files reviewed at latest revision, 14 unresolved discussions.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 842 at r4](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURq8vPUoxJ7SF1Op8Q:-KUT-8haoTpflheRK10V:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/81ae68a283919b92884be213980ed4ad95c60a72/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L842)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Тут все так само, як в `Завантажити протокол аукціону`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Comment by selurvedu** [comment]
Reviewed 2 of 4 files at r9, 3 of 3 files at r11, 4 of 4 files at r12, 1 of 1 files at r13, 7 of 7 files at r14, 2 of 2 files at r15, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 410 at r14](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUT1QF_rUCqTsECoUUe:-KUT1QFbaHAa5l2_y6H3:b-phmxbn) ([raw file](https://github.com/openprocurement/robot_tests/blob/97af61ac67baa96515d4a1b28ad50e1ec804c86c/op_robot_tests/tests_files/keywords.robot#L410)):*
> ```RobotFramework
> 
> 
> Отримати дані із документу пропозиції
> ```

Ківорд має бути в драйвері для кожного майданчика (це перенсти в openprocurement_client.robot).

---

*[op_robot_tests/tests_files/qualification.robot, line 233 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURebMEILRTuYvvfQds:-KUT-jOBvhZbw3eqQppq:b-cs3hea) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L233)):*
<details><summary><i>Previously, annawzz wrote…</i></summary>
> Done.
</details>
Undone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Comment by annawzz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 410 at r14](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUT1QF_rUCqTsECoUUe:-KUTBH3mt2G1E7lsuQ7z:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/97af61ac67baa96515d4a1b28ad50e1ec804c86c/op_robot_tests/tests_files/keywords.robot#L410)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Ківорд має бути в драйвері для кожного майданчика (це перенсти в openprocurement_client.robot).
</details>
Done.

---

*[op_robot_tests/tests_files/qualification.robot, line 233 at r2](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KURebMEILRTuYvvfQds:-KUTBINtdYJtfMJIaSyF:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/3fd5ebb71f518bcaed4508bd3b168e61a4bc386e/op_robot_tests/tests_files/qualification.robot#L233)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Undone.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Comment by selurvedu** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-:-KUTR4MjLU0rMbtIvdgn:b-jbsf8z)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 194 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/334#-KUTXTk4mBTbiUpvx9ms:-KUTXTk6Zet-Ptaqnc8X:b-1eyo1p) ([raw file](https://github.com/openprocurement/robot_tests/blob/c1333edd6a0d2d124909835639ecb35f012c177f/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L194)):*
> ```RobotFramework
>   ${tender}=  set_access_key  ${tender}  ${USERS.users['${username}'].access_token}
>   ${tender}=  Call Method  ${USERS.users['${username}'].client}  patch_tender  ${tender}
>   Порівняти об'єкти  ${prev_value}  ${USERS.users['${username}'].tender_data['${fieldname}']}
> ```

Це видає помилки вигляду:
```robotframework
Resolving variable '${USERS.users['Tender_Owner'].tender_data['tenderPeriod.startDate']}' failed: KeyError: 'tenderPeriod.startDate'
Resolving variable '${USERS.users['Tender_Owner'].tender_data['enquiryPeriod.endDate']}' failed: KeyError: 'enquiryPeriod.endDate'
Resolving variable '${USERS.users['Tender_Owner'].tender_data['guarantee']}' failed: KeyError: 'guarantee'
```
Праву частину треба робити через `Get From Object`, бо виходить щось типу `tender_data['tenderPeriod.startDate']`. Крім цього, там не вистачає `data`, тому код має виглядати якось так:
```robotframework
  ${new_value}=  Get From Object  ${tender.data}  ${fieldname}
  Порівняти об'єкти  ${prev_value}  ${new_value}
```

Крім цього, в тесткейсах на "неможливість" треба перевіряти, що помилка має не будь-який опис, а щось типу `Objects are not equal: ...`, інакше у нас будуть false positives, як вищенаведені.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/334)*

**Pull request merged**
