### PR TITLE
Add representation of document title to qualification.robot

### PR DESCRIPTION
**Pull request by mykhaly**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/166)

### CODE REVIEW

**Comment by mykhaly** [comment]
Прогнав локально singleitem від початку до кінця - все пройшло

**Comment by selurvedu** [comment]
+(in progress)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[op_robot_tests/tests_files/auction.robot, line 9 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFokyO7SxPxbi-td4V4:-KFokyO7SxPxbi-td4V5:1228742656) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/auction.robot#L9)):*
Для чого?

---

*[op_robot_tests/tests_files/keywords.robot, line 160 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFom1JGjafPeI18fbrh:-KFom1JHuS14cir31FNv:-1235181074) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L160)):*
Хм, то в нас auction, contract і qualification – без mode... Може простіше зробити там так?
```robotframework
*** Variables ***                                                                                                       
${mode}         ${None}
```

---

*[op_robot_tests/tests_files/keywords.robot, line 162 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFp_oqAHL0mrA_CVyeX:-KFp_oqBDrwmirFWvlT6:1842670726) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L162)):*
А для чого це взагалі треба?

---

*[op_robot_tests/tests_files/keywords.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFonxbCDikmndi0HT82:-KFonxbDFmEgDjWQ856w:1811188088) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L186)):*
З `Run Keyword And Ignore Error  Set to dictionary  ${artifact}  mode=${mode}` в dict'і може і не бути mode, тоді це провалиться. Тут або ще один `ignore error`, або вищеописаний варіант з `${mode}=  ${None}` в тих с’ютах, де його зараз нема.

---

*[op_robot_tests/tests_files/qualification.robot, line 27 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFol_bX0ASUUPmSPfFF:-KFol_bX0ASUUPmSPfFG:-1551821907) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L27)):*
Тут треба додати тег viewer і ще треба перевірити теги на відповідність в межах цього файлу.

---

*[op_robot_tests/tests_files/qualification.robot, line 30 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFoohuwQ5QAg_OpBzdb:-KFoohuxR9Vii7ABUWI6:1157927017) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L30)):*
Гарно підмічено.

---

*[op_robot_tests/tests_files/qualification.robot, line 33 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFolXnwwrsMhsWuJgdb:-KFolXnwwrsMhsWuJgdc:-604379982) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L33)):*
А теги?

---

*[op_robot_tests/tests_files/qualification.robot, line 37 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFolKRuGChiRY4K3PCx:-KFolKRuGChiRY4K3PCy:465326035) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L37)):*
Чому documents[1]?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-:-KFpaJlrvQot1hIUFgNt:1733137539)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[op_robot_tests/tests_files/auction.robot, line 9 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFokyO7SxPxbi-td4V4:-KFryfh1nfYVPLOcGy8d:1747480403) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/auction.robot#L9)):*
Без цього з артефакту не діставалися дані про документи (вони записуються в ${USERS.users['${provider(1)}']} ), бо змінних provider i provider1 не існувало

---

*[op_robot_tests/tests_files/keywords.robot, line 160 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFom1JGjafPeI18fbrh:-KFs0gAlqomEGVSTfWMl:529195136) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L160)):*
По-суті, в нас завжди буде змінна ${mode}, бо вона буде братися з артефакту. Тому можна викинути оце `Run keyword and ignore error`

---

*[op_robot_tests/tests_files/keywords.robot, line 162 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFp_oqAHL0mrA_CVyeX:-KFs19fmN7kOPLynYq8N:-130739437) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L162)):*
Щоб перевірити відображення документа в qualification.robot

---

*[op_robot_tests/tests_files/keywords.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFonxbCDikmndi0HT82:-KFs2l4pmdwmU7U6CE46:959333132) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L186)):*
Get variable value треба написати, я затупив. Тоді буде або старе значенння, або None.

---

*[op_robot_tests/tests_files/qualification.robot, line 27 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFol_bX0ASUUPmSPfFF:-KFs1Y57uZYmfMJCMZ63:5204865) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L27)):*
ОК

---

*[op_robot_tests/tests_files/qualification.robot, line 33 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFolXnwwrsMhsWuJgdb:-KFs1TytBJVdxl9RL48F:905124106) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L33)):*
Винен. Додам

---

*[op_robot_tests/tests_files/qualification.robot, line 37 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KFolKRuGChiRY4K3PCx:-KFs1Kl83AcBKaYmXHGd:-2110479226) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/qualification.robot#L37)):*
Бо документ оновлюється в singleItemTender. А оновлена версія не перезаписує стару, а створює новий документ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/166)*

**Comment by selurvedu** [comment]
Reviewed 2 of 4 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[op_robot_tests/tests_files/auction.robot, line 11 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KGDcviie6m1OlborxwQ:-KGDcvijk_X9A3jejJro:676271905) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/auction.robot#L11)):*
:-1:

---

*[op_robot_tests/tests_files/keywords.robot, line 169 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-KGDdPBrPfqM4xd6UQqM:-KGDdPBrPfqM4xd6UQqN:1029520204) ([raw file](https://github.com/openprocurement/robot_tests/blob/5637fbc0f6d426375c8cccb62ef4e7e24624c738/op_robot_tests/tests_files/keywords.robot#L169)):*
Bravo! :clap:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/166)*

**Comment by selurvedu** [comment]
Я зовсім заплутався в цих змінах... Воно ще не готове?

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-:-KGNr_wbTBTVMsK2A4YC:1855694250)*

**Comment by mykhaly** [comment]
Мертвонароджене, по ходу

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/166#-:-KKsTsGWuURwHzqBAz1p:-821285785)*

**Comment by mykhaly** [comment]
Старий і непотрібний pull-request. Закриваю, щоб не муляв очі.

**Pull request closed without merging**
