### PR TITLE
Wait to start of enquiry period

### PR DESCRIPTION
**Pull request by mykhaly**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/124)

### CODE REVIEW

**Comment by selurvedu** [comment]
В першому commit message є помилочка. :)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 478 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUxkaDjKFy2hURCcl:-KDeUxkbGvjO6Zp-olX_:760742017) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L478)):*
Заміни всюди `подання запитань` на `уточнень`.

---

*[op_robot_tests/tests_files/keywords.robot, line 488 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeVDhgmqyzoxBnqm_9:-KDeVDhh-9eqxE0uBPDb:592644486) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L488)):*
Цей блок коментарів дублюється. Можеш або видалити такий самий з `Дочекатись дати початку прийому пропозицій` і написати там `# XXX: HACK: Same as above`, або тут написати `# XXX: HACK: Same as below`, а той лишити як є. :)

---

*[op_robot_tests/tests_files/keywords.robot, line 498 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUzFtWY6kW0AjJlJJ:-KDeUzFtWY6kW0AjJlJK:-1069042656) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L498)):*
В допорогових закупівлях період уточнень є перед періодом подачі бідів, перемісти цей блок, щоб він був перед `Дочекатись дати початку прийому пропозицій`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-:-KDeVh2r0RCJH75GOsI1:-124555586)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 478 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUxkaDjKFy2hURCcl:-KDgxSYDwTmYYTKyLy6f:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L478)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 488 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeVDhgmqyzoxBnqm_9:-KDgwVXjGLmne_XWssiB:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L488)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 498 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUzFtWY6kW0AjJlJJ:-KDgwTi30O6uftX_lLaT:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L498)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/124)*

**Comment by selurvedu** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/keywords.robot, line 478 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUxkaDjKFy2hURCcl:-KDyCMMROcyU6OHtOY_L:1600320062) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L478)):*
Не `подання уточнень`, а `уточнень`. :)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/124)*

**Comment by mykhaly** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[op_robot_tests/tests_files/keywords.robot, line 478 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/124#-KDeUxkaDjKFy2hURCcl:-KE5kbWOrkXh1oi0Kk_z:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e41213118423ec93646fa4361389d143a12f633b/op_robot_tests/tests_files/keywords.robot#L478)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/124)*

**Comment by mykhaly** [comment]
https://github.com/openprocurement/robot_tests/pull/132

**Comment by selurvedu** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/124)*

**Pull request closed without merging**
