### PR TITLE
Remake tender creation and update modes

### PR DESCRIPTION
**Pull request by mykhaly**
Rewrite prepare_test_tender_data in alphabetical order
Update initial tenders data
Rename `test_meat_tender_data` -> `test_tender_data_meat`
Add new modes: `meat`, `multiItem`, `multiLot`
Update tender creation to work with this changes
Unify tender creation in that test suites.

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/109)

### CODE REVIEW

**Comment by Leits** [comment]
This branch has conflicts that must be resolved

**Comment by selurvedu** [comment]
Виріши конфлікти і можна приймати в devel. Перекидати на іншу гілку не треба.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/109#-:-KElwi4BMStb7Rks_2_-:461670559)*

**Comment by mykhaly** [comment]
Done.
Після вирішення конфліктів не тестив, чи нічого не зламалося.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/109#-:-KEphhpfRFKAs1m143Vx:-1054290052)*

**Comment by selurvedu** [comment]
:lgtm:
-conflicts

---

Reviewed 8 of 8 files at r2, 3 of 16 files at r3, 12 of 16 files at r8, 5 of 5 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/109#-:-KF4wfihW2dk43XvcBv0:-1672715923)*

**Pull request merged**
