### PR TITLE
Fix minimalStep.amount

### PR DESCRIPTION
**Pull request by mykhaly**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/149)

### CODE REVIEW

**Comment by selurvedu** [comment]
+qa

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 70 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KEgrhUcYYYsCwBckaIA:-KEgrhUdSaO6-GK7mKNu:-2056868991) ([raw file](https://github.com/openprocurement/robot_tests/blob/18ce928f7ae23dc1c3d99a8beea9f7e7b404d44f/op_robot_tests/tests_files/initial_data.py#L70)):*
А чого не так?
```python
round(random.uniform(0.005, 0.03) * value_amount, 2)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-:-KEgs3eu6lLgK6HWlFaK:160350294)*

**Comment by mykhaly** [comment]
*[op_robot_tests/tests_files/initial_data.py, line 70 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KEgrhUcYYYsCwBckaIA:-KEl0iDu72Lran5jJZqx:1928860307) ([raw file](https://github.com/openprocurement/robot_tests/blob/18ce928f7ae23dc1c3d99a8beea9f7e7b404d44f/op_robot_tests/tests_files/initial_data.py#L70)):*
я так не вмів. зараз перероблю

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149)*

**Comment by mykhaly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 70 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KEgrhUcYYYsCwBckaIA:-KEq-pK8b9TrGfIP_jUS:1476982227) ([raw file](https://github.com/openprocurement/robot_tests/blob/18ce928f7ae23dc1c3d99a8beea9f7e7b404d44f/op_robot_tests/tests_files/initial_data.py#L70)):*
Зробив.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149)*

**Comment by selurvedu** [comment]
:lgtm:
-qa

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-:-KF57Ic4M6iyoxp3QXvS:298221828)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[op_robot_tests/tests_files/initial_data.py, line 33 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KFj94r7gARgu_ftgFqp:-KFj94r8d4bVGnWhBv5f:-269222042) ([raw file](https://github.com/openprocurement/robot_tests/blob/9d1ef3788c91a76ef251b114d8373e2a35171629/op_robot_tests/tests_files/initial_data.py#L33)):*
Маю думку, що цей хардкод варто змінити на 
`value_amount = round(random.uniform(3000, 250000000000), 2) #max value equals to budget of Ukraine in hryvnias`
Чи це погана ідея?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149)*

**Comment by myroslav** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 33 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KFj94r7gARgu_ftgFqp:-KFjlMKMpBKnDqkI1rNC:1298554682) ([raw file](https://github.com/openprocurement/robot_tests/blob/9d1ef3788c91a76ef251b114d8373e2a35171629/op_robot_tests/tests_files/initial_data.py#L33)):*
Ідеально тестувати і певні значення і random. Можливо в нас має бути режим запуску з наперед визначеними початковими даними, щоб тестувати крайові випадки. Але можемо почати з random, і тоді слона "їсти" по кусочках.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-:-KFjlpQjgvhlyMn5Dt-O:1417088721)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 33 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KFj94r7gARgu_ftgFqp:-KFjqTScpGqGVBSL0QXA:-1594692210) ([raw file](https://github.com/openprocurement/robot_tests/blob/9d1ef3788c91a76ef251b114d8373e2a35171629/op_robot_tests/tests_files/initial_data.py#L33)):*
:+1:
@mykhaly, додавай в faker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149)*

**Comment by mykhaly** [comment]
*[op_robot_tests/tests_files/initial_data.py, line 33 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/149#-KFj94r7gARgu_ftgFqp:-KFmg5sZf8aluNMXYf1P:1665410557) ([raw file](https://github.com/openprocurement/robot_tests/blob/9d1ef3788c91a76ef251b114d8373e2a35171629/op_robot_tests/tests_files/initial_data.py#L33)):*
Цей рядок взятий з фейкера

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/149)*

**Pull request merged**
