### PR TITLE
Rename procurementMethodType for competitiveDialogue

### PR DESCRIPTION
**Pull request by gorserg**
Зміни пов'язані з перейменуванням типу процедури для  конкурентного діалогу

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/241)

### CODE REVIEW

**Comment by mykhaly** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/service_keywords.py, line 453 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/241#-KL20_Hy5BHQm6IS6u_Y:-KL20_Hy5BHQm6IS6u_Z:-1911907724) ([raw file](https://github.com/openprocurement/robot_tests/blob/f0204107e73353addfc65402f0eab5926982570f/op_robot_tests/tests_files/service_keywords.py#L453)):*
> ```Python
> def generate_test_bid_data(tender_data):
>     bid = test_bid_data()
>     if 'aboveThreshold' in tender_data.get('procurementMethodType', '') or 'competitiveDialogue' in tender_data.get('procurementMethodType', ''):
> ```

```
if 'aboveThreshold' or 'competitiveDialogue' in tender_data.get('procurementMethodType', ''):
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/241)*

**Comment by gorserg** [comment]
*[op_robot_tests/tests_files/service_keywords.py, line 453 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/241#-KL20_Hy5BHQm6IS6u_Y:-KL3BbpxT376YxoNB2pw:-1423873578) ([raw file](https://github.com/openprocurement/robot_tests/blob/f0204107e73353addfc65402f0eab5926982570f/op_robot_tests/tests_files/service_keywords.py#L453)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> ```
> if 'aboveThreshold' or 'competitiveDialogue' in tender_data.get('procurementMethodType', ''):
> ```
</details>
Done (rebase)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/241)*

**Comment by Leits** [comment]
[op_robot_tests/tests_files/service_keywords.py, line 453](https://reviewable.io/reviews/openprocurement/robot_tests/241#-KL20_Hy5BHQm6IS6u_Y:-KL3BbpxT376YxoNB2pw:-1423873578)
```
>>> if "a" or "b" in "ab": print True
True
>>> if "a" or "b" in "aa": print True
True
>>> if "a" or "b" in "bb": print True
True
>>> if "a" or "b" in "cc": print True
True
```
Це завжди буде `True`, бо не пуста стрічка завжди `True`.
Тому або повернути попереднє наочне порівняння, або замінити на : 
``` if any(type in tender_data.get('procurementMethodType', '') for type in ('aboveThreshold', 'competitiveDialogue')):```

**Comment by mykhaly** [comment]
Під час ребейсу зачепили не свій коміт. Треба забрати.

**Comment by gorserg** [comment]
повернув початковий варіант, прибрав лишній commit

**Comment by mykhaly** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/241#-:-KLQX_gHjppcbGPdTyHO:980077423)*

**Comment by testing-openprocurement-org** [comment]
My first comment.

**Pull request merged**
