### PR TITLE
Descriptions with id

### PR DESCRIPTION
**Pull request by Leits**
This change is [Review on Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/99)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 1 of 5 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 357 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/99#-KD7jpm6sfH88X3e5RR0:-KD7jpm7idgPOXIBJGez:-7790029) ([raw file](https://github.com/openprocurement/robot_tests/blob/79161764b20990207023da4322b40b98db0a9c9c/op_robot_tests/tests_files/initial_data.py#L357)):*
Чому complaint має префікс q?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/99)*

**Comment by Leits** [comment]
Оновив відносно змін у [#101 ](https://github.com/openprocurement/robot_tests/pull/101).

**Comment by Leits** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 357 \[r2\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/99#-KD7jpm6sfH88X3e5RR0:-KDN4RoIoDBbjNINaJ66:679120399) ([raw file](https://github.com/openprocurement/robot_tests/blob/79161764b20990207023da4322b40b98db0a9c9c/op_robot_tests/tests_files/initial_data.py#L357)):*
Забрав це. Complaint має свою uaid.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/99)*

**Comment by selurvedu** [comment]
:lgtm:

> Оновив відносно змін у #101 .

А #111 викликав нові конфлікти. :smile: 

---

Reviewed 1 of 5 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/99#-:-KDVvw0SGET1F-3m_zQS:1177575527)*

**Pull request merged**
