### PR TITLE
Del auction_bid and set_tender_periods

### PR DESCRIPTION
**Pull request by Leits**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/151)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 539 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/151#-KEltmyAqUF9rres1p72:-KEltmyBtfdWQRlrHyiP:-1914156269) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/initial_data.py#L539)):*
Є в імпортах в `service_keywords.py`, треба звідти викинути, а краще той список імпортів замінити на `*`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/151)*

**Comment by Leits** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 539 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/151#-KEltmyAqUF9rres1p72:-KEoiIHlUQEJkMvQoTT2:475114613) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/initial_data.py#L539)):*
Викинув auction_bid із імпорту, але імпорт залишив таким, як є. За pep 328 http://legacy.python.org/dev/peps/pep-0328/.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/151)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/151#-:-KF5L2gT5k-p24hLQ39v:1417088721)*

**Comment by selurvedu** [comment]
-qa

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/151#-:-KF5L5JA7JLlgCYDP49W:160352216)*

**Comment by mykhaly** [comment]
Я цей auction_bid теж видаляв в якомусь пр :/

**Comment by selurvedu** [comment]
Це PR в master, прийнято в devel. Прошу не закривати, він закриється автоматично.

**Pull request merged**
