### PR TITLE
Update lots test

### PR DESCRIPTION
**Pull request by Leits**
Використовує [#109](https://github.com/openprocurement/robot_tests/pull/109)
_____

This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/137)

### CODE REVIEW

**Comment by selurvedu** [comment]
Після прийняття #109 можна буде втягнути.

---

Reviewed 5 of 5 files at r1, 5 of 5 files at r2, 7 of 7 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 58 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEm9d_tI6MhZlbffroy:-KEm9d_u0xx_qVbcwvf5:1434971276) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L58)):*
Зроби і для обох провайдерів.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 115 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmBuH_WjoC2Un_rSOQ:-KEmBuHapDqxKyMK4004:417396841) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L115)):*
І тут теж.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 134 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmByAVK8CBeZeWFP88:-KEmByAVK8CBeZeWFP89:-859964084) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L134)):*
І тут.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-:-KEmFBqchWlhJ129ZiLR:-1412232025)*

**Comment by Leits** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 58 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEm9d_tI6MhZlbffroy:-KEokmUZZKaTFyxLBcmO:-183860662) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L58)):*
Done. Добавив ще owner-a, бо він має мати у кеші ці дані.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 115 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmBuH_WjoC2Un_rSOQ:-KEokp3UhwKJjaGMvYQu:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L115)):*
Done.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 134 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmByAVK8CBeZeWFP88:-KEol4FL4mvYcUR5COqs:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L134)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by selurvedu** [comment]
Reviewed 1 of 11 files at r5, 3 of 7 files at r6, 7 of 7 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 58 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEm9d_tI6MhZlbffroy:-KF54JRfqqWq3O5beQw-:-772785874) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L58)):*
Undone.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 115 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmBuH_WjoC2Un_rSOQ:-KF54KtAIpuZ2wdasuvg:-772785874) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L115)):*
Undone.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 134 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmByAVK8CBeZeWFP88:-KF54MV43VMg7Rz-iF_e:-772785874) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L134)):*
Undone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by Leits** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 58 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEm9d_tI6MhZlbffroy:-KF5bi2bO42GK0l0Wpr8:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L58)):*
Done.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 134 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmByAVK8CBeZeWFP88:-KF5cZVlrsDg_h4H2-Jd:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L134)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by Leits** [comment]
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[op_robot_tests/tests_files/multiLotTender.robot, line 115 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KEmBuH_WjoC2Un_rSOQ:-KF5cke2vLSj7yGFwht5:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/8c0a413e543a0ce5c27ff523c50ece1ada4db526/op_robot_tests/tests_files/multiLotTender.robot#L115)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r8, 7 of 7 files at r9, 7 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 207 \[r10\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KFBUaAolnJ0_h-eBtB4:-KFBUaAolnJ0_h-eBtB5:-1378537852) ([raw file](https://github.com/openprocurement/robot_tests/blob/b5de061783e16612446bb6b1164df620c7b469e3/op_robot_tests/tests_files/keywords.robot#L207)):*
Не зразу зрозумів, що це видаляється через те, що воно вже присутнє в #134.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 146 \[r12\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KFBXt8OGmrCFxXvEFPN:-KFBXt8PMBQ04nx8mN6L:1981277948) ([raw file](https://github.com/openprocurement/robot_tests/blob/5357a4492d4c0a1376b2c383009ef6064415b6f2/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L146)):*
:+1:

AFAICS, з цим не треба робити revert для #139. Прошу підтвердити.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 241 \[r12\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KFBfdzU3bI2e1vx7Bbw:-KFBfdzU3bI2e1vx7Bbx:1239265633) ([raw file](https://github.com/openprocurement/robot_tests/blob/5357a4492d4c0a1376b2c383009ef6064415b6f2/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L241)):*
А з цим – не треба revert для #140.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 146 \[r12\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KFBXt8OGmrCFxXvEFPN:-KFCntEQSZ3I9_-wd-9_:-1645026162) ([raw file](https://github.com/openprocurement/robot_tests/blob/5357a4492d4c0a1376b2c383009ef6064415b6f2/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L146)):*
Підтверджую.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 241 \[r12\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-KFBfdzU3bI2e1vx7Bbw:-KFCo-pT23xFTXCPNKwI:1598491732) ([raw file](https://github.com/openprocurement/robot_tests/blob/5357a4492d4c0a1376b2c383009ef6064415b6f2/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L241)):*
Підтведжую.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137)*

**Comment by selurvedu** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/137#-:-KFCoIiZuwbCpz-iSX5c:1417088721)*

**Pull request merged**
