### PR TITLE
Update initial data

### PR DESCRIPTION
**Pull request by Leits**
This change is [Review on Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/101)

### CODE REVIEW

**Comment by myroslav** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 646 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/101#-KCqtSb0qHpDe_lE5goC:-KCqtSb0qHpDe_lE5goD:-1379744661) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7869f1a3dcdce21b4866cf32417c551d2de257b/op_robot_tests/tests_files/initial_data.py#L646)):*
А від тих 2000 додаткових нічого не поламається?

До речі, в майданчиків є обмеження на бюджет закупівлі, і мінімум - 3000 грн в нас теж всі суми мали б бути більші

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/101)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/initial_data.py, line 646 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/101#-KCqtSb0qHpDe_lE5goC:-KD--qhgD5hbLiZLBEI4:1276357323) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7869f1a3dcdce21b4866cf32417c551d2de257b/op_robot_tests/tests_files/initial_data.py#L646)):*
Нічого не ламається. Зробив, бо у пропозиції для лоту amount максимально може досягнути 1999. Треба дізнатися це у всіх майданчиків і тоді уже підправимо.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/101)*

**Comment by selurvedu** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/101)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[op_robot_tests/tests_files/initial_data.py, line 646 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/101#-KCqtSb0qHpDe_lE5goC:-KEm_6ABKd-yG2_Refei:1953816827) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7869f1a3dcdce21b4866cf32417c551d2de257b/op_robot_tests/tests_files/initial_data.py#L646)):*
Вони самі нам про це скажуть. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/101)*

**Pull request merged**
