### PR TITLE
Bug fixes for full dgf scenarios

### PR DESCRIPTION
**Pull request by annawzz**
1. Add handling errors in `Отримати дані із документу пропозиції` and `Отримати кількість документів в ставці`.
2. Add generation of fake valid URLs for VDR (example - https://dummyimage.com/700x400/964f96/363636)
3. Change test case `Відображення закінчення періоду прийому пропозицій лоту` (according to brokers needs)

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/369)

### CODE REVIEW

**Comment by selurvedu** [comment]
> reflection

Віддзеркалення FTW!

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 83 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWZ9brn_bQD8sSCPou1:-KWZ9brow-0KmVvTkd-f:bd2u0t7) ([raw file](https://github.com/openprocurement/robot_tests/blob/6e23c7779c40c224d816829dbed9a67e17325c8b/op_robot_tests/tests_files/initial_data.py#L83)):*
> ```Python
>     size_x =  random.randint(10, 1000)
>     size_y =  random.randint(10, 1000)
>     return base + str(size_x) + 'x' + str(size_y) + '/' + str(background_color) + '/' + str(font_color)
> ```

```python
return '{0}/{1}x{2}/{3}/{4}.png'.format(base, size_x, size_y, background_color, font_color)
```
І в base забрати слеш в кінці.

---

*[op_robot_tests/tests_files/keywords.robot, line 406 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWZANfyAMuhptRD6w7S:-KWZANfyAMuhptRD6w7T:bc5a76r) ([raw file](https://github.com/openprocurement/robot_tests/blob/d306c833041362ecfaa69ae8b8087c2a910eeb6e/op_robot_tests/tests_files/keywords.robot#L406)):*
> ```RobotFramework
>   :FOR  ${document_index}  IN RANGE  ${number_of_documents}
>   \  ${field_value}=  Run As  ${username}  Отримати дані із документу пропозиції  ${tender_uaid}  ${bid_index}  ${document_index}  ${field}
>   \  ${match_in_document}=  Set Variable If  '${field_value}'=='${value}'  True  False
> ```

Заміни `True` на `${True}` і `False` на `${False}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-:-KWZAXBdbIy6a2waTM3E:blavjj9)*

**Comment by annawzz** [comment]
Змінила на display

---

Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 83 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWZ9brn_bQD8sSCPou1:-KWcXQ01ijvijw1uKkrJ:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/6e23c7779c40c224d816829dbed9a67e17325c8b/op_robot_tests/tests_files/initial_data.py#L83)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> ```python
> return '{0}/{1}x{2}/{3}/{4}.png'.format(base, size_x, size_y, background_color, font_color)
> ```
> І в base забрати слеш в кінці.
</details>
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 406 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWZANfyAMuhptRD6w7S:-KWcXOALyiXpTKIS9klo:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/d306c833041362ecfaa69ae8b8087c2a910eeb6e/op_robot_tests/tests_files/keywords.robot#L406)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Заміни `True` на `${True}` і `False` на `${False}`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-:-KWhC973N2nM4TH9j7ab:b-klo207)*

**Comment by selurvedu** [comment]
+@selurvedu +qa
This is good enough, but it needs be perfect. :smile:

---

Reviewed 4 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, 4 of 4 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 609 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnFHg1ZFIZqF6PWFqo:-KWnFHg2xHLipLr-uDlB:br7o1sm) ([raw file](https://github.com/openprocurement/robot_tests/blob/98e71f44195bdfe9cfd58cd8811e8ff30711576e/op_robot_tests/tests_files/base_keywords.robot#L609)):*
> ```RobotFramework
> 
> 
> Можливість завантажити протокол аукціону в пропозицію користувачем ${username} в ставку ${bid_index}
> ```

`в пропозицію`

---

*[op_robot_tests/tests_files/keywords.robot, line 593 at r9](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnHKOQB-IL1mkAQGcP:-KWnHKOQB-IL1mkAQGcQ:b-4hmnge) ([raw file](https://github.com/openprocurement/robot_tests/blob/38fa9c0ae3beb41e42b91ac9d39203acc85e312b/op_robot_tests/tests_files/keywords.robot#L593)):*
> ${status}
> Run Keyword And Ignore Error
Напевно що зайве. Якщо без цього не працює, то я дуже хочу побачити log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-:-KWnHp7LOlUPslD5y5BN:b-tzd6dq)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 136 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnOzg4t9_6X00v0jck:-KWnOzg5mx1IDUbYWiY5:b7uwtuk) ([raw file](https://github.com/openprocurement/robot_tests/blob/b5499c31f5ebc5ff8596fb00b3338346cb01693a/op_robot_tests/tests_files/openProcedure.robot#L136)):*
> ```RobotFramework
>   ...      ${USERS.users['${viewer}'].broker}
>   ...      tender_view_tenderPeriod  level2
>   Звірити дату тендера із значенням  ${viewer}  ${TENDER['TENDER_UAID']}  ${USERS.users['${tender_owner}'].initial_data.data.auctionPeriod.startDate}  tenderPeriod.endDate
> ```

А як же та проблема з неспівпадінням? Не прийму я таке...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369)*

**Comment by annawzz** [comment]
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 609 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnFHg1ZFIZqF6PWFqo:-KWr7EUUTyWZplPjB1Z2:b-yczppf) ([raw file](https://github.com/openprocurement/robot_tests/blob/98e71f44195bdfe9cfd58cd8811e8ff30711576e/op_robot_tests/tests_files/base_keywords.robot#L609)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> `в пропозицію`
</details>
Змінила на
```robot
Можливість завантажити протокол аукціону в пропозицію ${bid_index} користувачем ${username}
```

---

*[op_robot_tests/tests_files/keywords.robot, line 593 at r9](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnHKOQB-IL1mkAQGcP:-KWrFmVrWc1-3DWXD0ab:b2o2bvx) ([raw file](https://github.com/openprocurement/robot_tests/blob/38fa9c0ae3beb41e42b91ac9d39203acc85e312b/op_robot_tests/tests_files/keywords.robot#L593)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> > ${status}
> > Run Keyword And Ignore Error
> Напевно що зайве. Якщо без цього не працює, то я дуже хочу побачити log.
</details>
Ок.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 136 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnOzg4t9_6X00v0jck:-KWrFw5emACQxwlG1bnd:b-ujxdhg) ([raw file](https://github.com/openprocurement/robot_tests/blob/b5499c31f5ebc5ff8596fb00b3338346cb01693a/op_robot_tests/tests_files/openProcedure.robot#L136)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> А як же та проблема з неспівпадінням? Не прийму я таке...
</details>
Збільшила точність для перевірки до 80 секунд, тимчасове рішення.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369)*

**Comment by selurvedu** [comment]
:lgtm_strong:
Perfect! :shipit:

---

Reviewed 7 of 7 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 3 of 3 files at r15, 4 of 4 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 2 of 2 files at r19.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 609 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnFHg1ZFIZqF6PWFqo:-KWrOWzneP8SziXL80Hr:bb6ywmx) ([raw file](https://github.com/openprocurement/robot_tests/blob/98e71f44195bdfe9cfd58cd8811e8ff30711576e/op_robot_tests/tests_files/base_keywords.robot#L609)):*
<details><summary><i>Previously, annawzz wrote…</i></summary>
> Змінила на
> ```robot
> Можливість завантажити протокол аукціону в пропозицію ${bid_index} користувачем ${username}
> ```
</details>
LGTM

---

*[op_robot_tests/tests_files/keywords.robot, line 593 at r9](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnHKOQB-IL1mkAQGcP:-KWrOrx6llGJ_WJrOPjl:b32w0x) ([raw file](https://github.com/openprocurement/robot_tests/blob/38fa9c0ae3beb41e42b91ac9d39203acc85e312b/op_robot_tests/tests_files/keywords.robot#L593)):*
<details><summary><i>Previously, annawzz wrote…</i></summary>
> Ок.
</details>
OK

---

*[op_robot_tests/tests_files/openProcedure.robot, line 136 at r5](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KWnOzg4t9_6X00v0jck:-KWrNXnJqFWp0TClnfrc:baw7vub) ([raw file](https://github.com/openprocurement/robot_tests/blob/b5499c31f5ebc5ff8596fb00b3338346cb01693a/op_robot_tests/tests_files/openProcedure.robot#L136)):*
<details><summary><i>Previously, annawzz wrote…</i></summary>
> Збільшила точність для перевірки до 80 секунд, тимчасове рішення.
</details>
OK, але замість `${Empty}` можна було не додавати, а натомість написати `accuracy=80`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-:-KWrPGcznANmzKMECClk:b649olk)*

**Comment by mykhaly** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 564 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI6tDO43pcEUsM687V:-KXI6tDO43pcEUsM687W:b8xxmgt) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/base_keywords.robot#L564)):*
> ```RobotFramework
>   Set To Dictionary  ${USERS.users['${username}'].bidresponses}  resp=${resp}
>   Run Keyword If  '${MODE}'=='dgfFinancialAssets'
>   ...             Можливість завантажити фінансову лізенцію в пропозицію користувачем ${username}
> ```

Not perfect :)
ліЦеНзію :)

---

*[op_robot_tests/tests_files/initial_data.py, line 75 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI73WwkKt9TXik4Gt-:-KXI73Wxbu2FyXudQF0R:b-690b23) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/initial_data.py#L75)):*
> ```Python
> 
> def create_fake_vdr_url():
>     # Generate fake valid URL for VDR,
> ```

Документацію до пітонівських функцій бажано писати багаторядковим, а не звичайним коментарем.
Тобто, зробити отак:
```
"""
Generate fake valid URL for VDR with random size, font and background color for image.
Example: https://dummyimage.com/700x400/964f96/363636
"""
```

---

*[op_robot_tests/tests_files/initial_data.py, line 79 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI7XCbr-F6dyy6mLgL:-KXI7XCbr-F6dyy6mLgM:b-of70e8) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/initial_data.py#L79)):*
> ```Python
>     # Example: https://dummyimage.com/700x400/964f96/363636
>     base = 'https://dummyimage.com'
>     background_color = ''.join([random.choice('0123456789ABCDEF') for x in range(6)])
> ```

Якщо непотрібна при ітеруванні, раджу називати її `_`. Можливо, це прописано в якомусь пепі, але я не впевнений.
А також, є така штука, як random.sample(list, number_of_items)
Раджу тут скористатися нею.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 135 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI8x555x_9JbodI-oj:-KXI8x555x_9JbodI-ok:b-ijkg30) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/openProcedure.robot#L135)):*
> ```RobotFramework
>   ...      viewer
>   ...      ${USERS.users['${viewer}'].broker}
>   ...      tender_view_tenderPeriod  level2
> ```

Якщо наверху додали `_startDate`, то було б логічно тут додати `_endDate`.

---

*[op_robot_tests/tests_files/qualification.robot, line 238 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI9DC7A3BzKEIkka-C:-KXI9DC8jhJ_isPCOsuV:b-87rcmj) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/qualification.robot#L238)):*
> ```RobotFramework
>   ...  qualification_add_auction_protocol_to_bid  level1
>   [Teardown]  Оновити LAST_MODIFICATION_DATE
>   Можливість завантажити протокол аукціону в пропозицію 0 користувачем ${provider}
> ```

Мені здається, що `в 0 пропозицію` виглядає читабельніше.

---

*[op_robot_tests/tests_files/qualification.robot, line 293 at r19](https://reviewable.io:443/reviews/openprocurement/robot_tests/369#-KXI9PE1TIsRADC_6_gI:-KXI9PE1TIsRADC_6_gJ:brkj87c) ([raw file](https://github.com/openprocurement/robot_tests/blob/ea7842f9daa5c6454bcbcf7a081d7e91e0e0c613/op_robot_tests/tests_files/qualification.robot#L293)):*
> ```RobotFramework
>   ...  qualification_add_auction_protocol_to_bid  level1
>   [Teardown]  Оновити LAST_MODIFICATION_DATE
>   Можливість завантажити протокол аукціону в пропозицію -1 користувачем ${provider1}
> ```

В тегах замінити `provider` на `provider1`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/369)*

**Comment by annawzz** [comment]
Врахую і поправлю, як буде час і можливість.

**Pull request merged**
