### PR TITLE
Meat auction

### PR DESCRIPTION
**Pull request by Leits**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/156)

### CODE REVIEW

**Comment by selurvedu** [comment]
:lgtm:
+conflicts

Тестував? Працює?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/156#-:-KFDCAtigqrHDmPSDPZy:945048493)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/156)*

**Comment by Leits** [comment]
Працює.

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/156#-:-KFJW4Xp0HuCgbPB40uT:-781336514)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/156)*

**Pull request merged**
