### PR TITLE
Create and delete items by item id

### PR DESCRIPTION
**Pull request by Leits**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/134)

### CODE REVIEW

**Comment by selurvedu** [comment]
+(backward incompatible)

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 149 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECcYwAqF6c8jDpkucl:-KECcYwAqF6c8jDpkucm:-81987978) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/keywords.robot#L149)):*
Додай 2 порожні рядки перед і після замість одного.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 181 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECd-V1hfb9LhaRvt4r:-KECd-V2n1kvecmAqrxa:-1285117302) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L181)):*
`нової позиції`

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECdKheSs7xG6W7afDq:-KECdKheSs7xG6W7afDr:1117365260) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L186)):*
Чому тут і нижче не передати `${USERS.users['${tender_owner}'].item_data.item_id}` напряму? Чи потрібна додаткова змінна?

---

*[op_robot_tests/tests_files/service_keywords.py, line 358 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECbygRtnsQkbxCuvjY:-KECbygSXyGneFRR8qC6:-259534316) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/service_keywords.py#L358)):*
Поясни, що це робить.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-:-KECdZwxGfv30_Hr71xY:200325045)*

**Comment by selurvedu** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/134)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 149 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECcYwAqF6c8jDpkucl:-KEQrr9kUYs_TxDymIKa:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/keywords.robot#L149)):*
Done.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 181 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECd-V1hfb9LhaRvt4r:-KEQrqOBNUgfG2hR6fVL:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L181)):*
Done.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECdKheSs7xG6W7afDq:-KEQqso7mA1pBO7ItUgx:-221929628) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L186)):*
Вчинив за аналогією із запитаннями. Можу це виправити.

---

*[op_robot_tests/tests_files/service_keywords.py, line 358 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECbygRtnsQkbxCuvjY:-KEQpynBolnLxpiQZYQh:-820249383) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/service_keywords.py#L358)):*
Якщо переданий список об'єктів пустий, визначаємо даний об'єкт першим. У іншому випадку, перебираємо список. Якщо серед об'єкт не знайдено, визначаємо його як наступний у списку. 
Усуває помилку, коли список існує, але об'єкту немає у списку і йому присвоюється нульовий індекс.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/134)*

**Comment by selurvedu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 149 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECcYwAqF6c8jDpkucl:-KEmKmBoPLVEavVuwAJ8:-772785874) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/keywords.robot#L149)):*
Undone.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 181 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECd-V1hfb9LhaRvt4r:-KEmKlBOt_mpXkQElpwG:-1079555410) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L181)):*
Undone. Перевір кожен заголовок, будь ласка.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECdKheSs7xG6W7afDq:-KEmKhOiKmI86iwp6t1t:-926671657) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L186)):*
Виправляй.

---

*[op_robot_tests/tests_files/service_keywords.py, line 358 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECbygRtnsQkbxCuvjY:-KEmKPGktnOml_YZ3gct:-1135975204) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/service_keywords.py#L358)):*
Тобто ми припускаємо, що об’єкт, якого ще нема в лісті, буде мати індекс останнього елемента плюс один, а якщо ліст був порожній, то індекс буде рівний нулю. Зрозуміло.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/134)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 149 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECcYwAqF6c8jDpkucl:-KEogHraQvo0HXr_widC:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/keywords.robot#L149)):*
Done.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 181 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECd-V1hfb9LhaRvt4r:-KEogJ8LufVL5aNLW5Eq:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L181)):*
Done.

---

*[op_robot_tests/tests_files/multiItemTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-KECdKheSs7xG6W7afDq:-KEogFDAGeNwIBsXIVwD:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9e5ea6279499a3198fc2e08c114c85102d65227d/op_robot_tests/tests_files/multiItemTender.robot#L186)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/134)*

**Comment by selurvedu** [comment]
:lgtm:
-qa -(backward incompatible)

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/134#-:-KF50sP-t-alPB78kE5a:-503526646)*

**Pull request merged**
