### PR TITLE
Update openProcedure to support eauction (mode dgf)

### PR DESCRIPTION
**Pull request by bubanoid**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/316)

### CODE REVIEW

**Comment by mykhaly** [comment]
Так, як один рядок змінюється в двох комітах, то треба зробити ребейс :)
Або ресетнути останні коміт і зробити аменд, up to you.
Так як це перший раз, то можу підійти сам і показати, як то робиться.
Але це все є в гуглі, тому можна постаратися самій(ому).

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSHZbezR1ijhTgQ7pQ8:b-pntbkf)*

**Comment by mykhaly** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 375 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMS-4s1yBAemQ1JyPr:-KSMS-4s1yBAemQ1JyPs:bhh7g77) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/initial_data.py#L375)):*
> ```Python
>     # Therefore, we pass a nondefault list of periods to `test_tender_data()`.
>     data = test_tender_data(params, ('tender',))
>     # data['procurementMethodType'] = 'aboveThresholdEU'
> ```

Якщо це непотрібно - видаляй. В репозиторії такого точно не має бути.
Файли не повністю можна додавати з допомогою опції `-p` в `git add`.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 19 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSPivngro7ubGuZoQ:-KSMSPivngro7ubGuZoR:bck8wmb) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L19)):*
> ```RobotFramework
> 
> 
> # Отримати internal id по UAid
> ```

А це чому закоментовано?

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 8 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSXhNb5anAyqFY1_e:-KSMSXhNb5anAyqFY1_f:b-5t2fdy) ([raw file](https://github.com/openprocurement/robot_tests/blob/81fd01efa85515cd49a53e7530b2d296c2907692/op_robot_tests/tests_files/op_faker/op_faker.py#L8)):*
> ```Python
> import os
> ```

Оце дарма видалила.

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 100 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSdKkLzogJmaXXP-7:-KSMSdKkLzogJmaXXP-8:b-68xub2) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/op_faker/op_faker.py#L100)):*
> ```Python
> 
>         :param cav_group: gives possibility to generate items
>             from a specific cav group. cpv group is three digits
> ```

завтик з одною буквою **c** і одною **p**.

---

*[op_robot_tests/tests_files/op_faker/op_faker_data.json, line 2900 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMTl3Qs7lyGyR-8DTQ:-KSMTl3RpjwFIRGhiAw2:bsjigpr) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/op_faker/op_faker_data.json#L2900)):*
> ```JSON
>             "cav_id": "34100000-8",
>             "description": "Мототранспортні засоби",
>             "description_ru": "ММММ",
> ```

Ну тут можна було би вже і написати нормально)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316)*

**Comment by mykhaly** [comment]
:lgtm:
Мені подобається. Зараз локально в себе перевірю, чи все окей, і якщо так, то очікую на зміни в коментарях і приймаю пул-реквест.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSMTv85t3AInzCBuBXd:b-52bl48)*

**Comment by selurvedu** [comment]
Останній commit message не є валідним реченням. :)

І "Change to robot files for eauction compatibility", "Change to python files for CAV compatibility" краще буде звучати якщо "to" замінити на "the".

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 6 of 6 files at r4, 3 of 3 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 378 at r6](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSWgbfurFb3YZcc5z9W:-KSWgbfurFb3YZcc5z9X:b-grqnht) ([raw file](https://github.com/openprocurement/robot_tests/blob/dc0f2e7f55b1e0aec789ba5bcbb61392de450fe6/op_robot_tests/tests_files/initial_data.py#L378)):*
> ```Python
>     data['title_en'] = "[TESTING]"
>     for item_number, item in enumerate(data['items']):
>          item['description_en'] = "Test item #{}".format(item_number)
> ```

Цей пробіл зайвий.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSWhlBt6Lux2s3Fvcpq:bga0229)*

**Comment by annawzz** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 375 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMS-4s1yBAemQ1JyPr:-KSMvZyXLAIzwwaMzJAm:b-c2vu7g) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/initial_data.py#L375)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Якщо це непотрібно - видаляй. В репозиторії такого точно не має бути.
> Файли не повністю можна додавати з допомогою опції `-p` в `git add`.
</details>
Забрала виділення коментарем

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 19 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSPivngro7ubGuZoQ:-KSMzlq9uxbCCMTMvqwR:bv6q3p1) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L19)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> А це чому закоментовано?
</details>
забрала лишній коментар

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 8 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSXhNb5anAyqFY1_e:-KSMm-zKIBQthXGMDyL6:b-b8w9l1) ([raw file](https://github.com/openprocurement/robot_tests/blob/81fd01efa85515cd49a53e7530b2d296c2907692/op_robot_tests/tests_files/op_faker/op_faker.py#L8)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Оце дарма видалила.
</details>
Повернула назад пусту стрічку.

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 100 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSdKkLzogJmaXXP-7:-KSMwsnRDRAlM3L5gpLA:b-86xyro) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/op_faker/op_faker.py#L100)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> завтик з одною буквою **c** і одною **p**.
</details>
Поправила cpv на cav

---

*[op_robot_tests/tests_files/op_faker/op_faker_data.json, line 2900 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMTl3Qs7lyGyR-8DTQ:-KSMz9R4fEsGjaJaunzZ:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/op_faker/op_faker_data.json#L2900)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Ну тут можна було би вже і написати нормально)
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316)*

**Comment by mykhaly** [comment]
Можна приймати пул-реквест? Чи будуть ще якісь зміни?

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 19 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSPivngro7ubGuZoQ:-KSaFjTC5DUmsw-ym_Uj:b-z3rykm) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L19)):*
<details><summary><i>Previously, annawzz wrote…</i></summary>
> забрала лишній коментар
</details>
Ти його просто видалила. А треба було лише забрати коментування і залишити самі рядки.
Чи я щось неправильно розумію?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSaGdcyXzw8PbbDjyOt:br4z425)*

**Comment by annawzz** [comment]
може ще не приймай ПР, бо я вже зробила так, що повністю проходить below_simple, і зараз працюю над тим щоб проходила повністю Below. ті всі зміни ще не повністю готові, я їх ще не комітила. 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 19 at r3](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSMSPivngro7ubGuZoQ:-KSaJ8D4HD5hNqRq5uMm:bcwjy1t) ([raw file](https://github.com/openprocurement/robot_tests/blob/8d1a7a5bfc4eec971fca56a86b203108d0a18e01/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L19)):*
<details><summary><i>Previously, mykhaly (Yurii Mykhalchuk) wrote…</i></summary>
> Ти його просто видалила. А треба було лише забрати коментування і залишити самі рядки.
> Чи я щось неправильно розумію?
</details>
Ні, там треба було повінстю видалити той комент. | його додала собі з SingleItem,  і правила по аналогії кейс який вже був в openProcedure. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSaJzavyxfmfIjTwJDG:b-f52h6m)*

**Comment by annawzz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 378 at r6](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSWgbfurFb3YZcc5z9W:-KSaLI_CDtardUwzJMIC:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/dc0f2e7f55b1e0aec789ba5bcbb61392de450fe6/op_robot_tests/tests_files/initial_data.py#L378)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Цей пробіл зайвий.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316)*

**Comment by mykhaly** [comment]
@annawzz FYI:
Артиклі не використовуються з множиною (~~the~~ robot files).

**Comment by annawzz** [comment]
Ok

---

Review status: 3 of 12 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSgEFAhIOfQUEXVPn8G:b32w1t)*

**Comment by selurvedu** [comment]
Reviewed 4 of 4 files at r8, 2 of 2 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, 1 of 1 files at r15, 2 of 2 files at r16, 2 of 2 files at r17, 3 of 3 files at r18.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 74 at r16](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlfCSg81Q_rwWyC9Wl:-KSlfCSg81Q_rwWyC9Wm:b-69xc0g) ([raw file](https://github.com/openprocurement/robot_tests/blob/086f79ccadff28fbc508c43811c73cfc590d657b/op_robot_tests/tests_files/initial_data.py#L74)):*
> ```Python
>         },
>         "items": [],
>         #"features": []
> ```

Видаляй.

---

*[op_robot_tests/tests_files/initial_data.py, line 107 at r16](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlfAxGDlLRRXVFCSOe:-KSlfAxGDlLRRXVFCSOf:b-n01s6v) ([raw file](https://github.com/openprocurement/robot_tests/blob/086f79ccadff28fbc508c43811c73cfc590d657b/op_robot_tests/tests_files/initial_data.py#L107)):*
> ```Python
>     #     data['features'].append(new_feature)
>     # if not data['features']:
>     #     del data['features']
> ```

І тут видаляй.

---

*[op_robot_tests/tests_files/keywords.robot, line 401 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlg85du6jx4oDjD5kA:-KSlg85du6jx4oDjD5kB:b-o43i9v) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/keywords.robot#L401)):*
> ```RobotFramework
>   Should Not Be Equal  ${right}  ${None}
>   Should Be Equal  ${left}  ${right}  msg=Objects are not equal
> ```

<comment mode="@mykhaly">
Перед ключовим словом і після нього, так само як і з тесткейсами, має бути два порожні рядки.
</comment>

---

*[op_robot_tests/tests_files/keywords.robot, line 665 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlg3fKbDZCkvSy74PA:-KSlg3fLOFZfJTLJGB8-:b-40fkp5) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/keywords.robot#L665)):*
> ```RobotFramework
> #   ...      ${username}
> #   ...      ${tender_uaid}
> #   ...      active.auction
> ```

Видаляй закоментоване.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 1000 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSl_eleLPiOIp7UXtpi:-KSl_elfLKOMwckiQFwP:b-x3k6ir) ([raw file](https://github.com/openprocurement/robot_tests/blob/117f73fa5997ff0645bb96fb16efac3f675c3a61/op_robot_tests/tests_files/openProcedure.robot#L1000)):*
> ```RobotFramework
>   ...      modify_bid_after_tendering_period_by_provider1
>   [Setup]  Дочекатись дати закінчення прийому пропозицій  ${provider1}  ${TENDER['TENDER_UAID']}
>   Run Keyword And Expect Error  *  Можливість збільшити пропозицію до 105 відсотків користувачем ${provider1}
> ```

Заміни на `Require Failure`.

---

*[op_robot_tests/tests_files/openProcedure.robot, line 321 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSljdfgem5QVPLVWe1R:-KSljdfgem5QVPLVWe1S:b-du2uu9) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/openProcedure.robot#L321)):*
> ```RobotFramework
>   ...      ${USERS.users['${provider}'].broker}
>   ...      ask_question_to_tender
>   #[Setup]  Дочекатись дати початку очікування  ${provider}  ${TENDER['TENDER_UAID']}
> ```

Видали цей рядок.

---

*[op_robot_tests/tests_files/service_keywords.py, line 43 at r11](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSle3yLxzaNDCG0ud9E:-KSle3yMDD-pPhTkrLOl:b-quceoy) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7394fa47a5a4479501ea3dca49adf41348bb5e6/op_robot_tests/tests_files/service_keywords.py#L43)):*
> ```Python
>     test_tender_data_openeu,
>     test_tender_data_openua,
>     test_tender_data_dgf,
> ```

Відсортуй за алфавітом

---

*[op_robot_tests/tests_files/service_keywords.py, line 290 at r11](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSle6i5ZIcXiJtNzRbP:-KSle6i5ZIcXiJtNzRbQ:b-sgfnzj) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7394fa47a5a4479501ea3dca49adf41348bb5e6/op_robot_tests/tests_files/service_keywords.py#L290)):*
> ```Python
>     elif mode == 'belowThreshold':
>         return munchify({'data': test_tender_data(tender_parameters)})
>     elif mode == 'dgf':
> ```

І це теж

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 499 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlaPpyFgc-ZPe04AnJ:-KSlaPpzCbSGaIL1Zdtm:b9pfhgw) ([raw file](https://github.com/openprocurement/robot_tests/blob/117f73fa5997ff0645bb96fb16efac3f675c3a61/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L499)):*
> ```RobotFramework
>   \    ${code}=  Get Variable Value  ${tender.data.features[${feature_index}].code}
>   \    Set To Dictionary  ${bid.data.parameters[${index}]}  code=${code}
>   ${bid}=  Set Variable  ${bid}
> ```

Зайве.

---

*[robot_tests_arguments/dgf_other.txt, line 4 at r18](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlkItRCQwVCN0mJSep:-KSlkItSgJLzS6HcDPFH:bfmx6e5) ([raw file](https://github.com/openprocurement/robot_tests/blob/294d27a0197aa2c5050d30ae9b12f75d112e2cec/robot_tests_arguments/dgf_other.txt#L4)):*
> ```
> 
> -v NUMBER_OF_ITEMS:1
> -v NUMBER_OF_LOTS:0
> ```

MEAT і LOTS можна і треба викинути.

---

*[robot_tests_arguments/dgf_other_simple.txt, line 4 at r14](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlepzhB6HGcFXxrWo9:-KSlepzhB6HGcFXxrWoA:bfmx6e5) ([raw file](https://github.com/openprocurement/robot_tests/blob/45cb072f3cef2ed40814493ef2696d30740eea42/robot_tests_arguments/dgf_other_simple.txt#L4)):*
> ```
> 
> -v NUMBER_OF_ITEMS:1
> -v NUMBER_OF_LOTS:0
> ```

MEAT і LOTS можна і треба викинути.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316)*

**Comment by annawzz** [comment]
Review status: 5 of 13 files reviewed at latest revision, 12 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 74 at r16](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlfCSg81Q_rwWyC9Wl:-KSlpx_jZ6aGBTsdmtW9:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/086f79ccadff28fbc508c43811c73cfc590d657b/op_robot_tests/tests_files/initial_data.py#L74)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Видаляй.
</details>
done

---

*[op_robot_tests/tests_files/initial_data.py, line 107 at r16](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlfAxGDlLRRXVFCSOe:-KSloEYnjvw1ynWDMMEI:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/086f79ccadff28fbc508c43811c73cfc590d657b/op_robot_tests/tests_files/initial_data.py#L107)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> І тут видаляй.
</details>
done

---

*[op_robot_tests/tests_files/keywords.robot, line 401 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlg85du6jx4oDjD5kA:-KSloLwRuKQTwY6ga7KK:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/keywords.robot#L401)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> <comment mode="@mykhaly">
> Перед ключовим словом і після нього, так само як і з тесткейсами, має бути два порожні рядки.
> </comment>
</details>
done

---

*[op_robot_tests/tests_files/keywords.robot, line 665 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlg3fKbDZCkvSy74PA:-KSlooBoakMWPXvZoq5Q:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/keywords.robot#L665)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Видаляй закоментоване.
</details>
done

---

*[op_robot_tests/tests_files/openProcedure.robot, line 1000 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSl_eleLPiOIp7UXtpi:-KSlq3OzzFDEQ6nqan1s:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/117f73fa5997ff0645bb96fb16efac3f675c3a61/op_robot_tests/tests_files/openProcedure.robot#L1000)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Заміни на `Require Failure`.
</details>
done

---

*[op_robot_tests/tests_files/openProcedure.robot, line 321 at r17](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSljdfgem5QVPLVWe1R:-KSlp00xC5rt1lovm6jr:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/d17a5728427e4fd41ea92847ace71f6f3407cb59/op_robot_tests/tests_files/openProcedure.robot#L321)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Видали цей рядок.
</details>
done

---

*[op_robot_tests/tests_files/service_keywords.py, line 43 at r11](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSle3yLxzaNDCG0ud9E:-KSlqyUnuvEI8yPiT41T:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7394fa47a5a4479501ea3dca49adf41348bb5e6/op_robot_tests/tests_files/service_keywords.py#L43)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Відсортуй за алфавітом
</details>
done

---

*[op_robot_tests/tests_files/service_keywords.py, line 290 at r11](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSle6i5ZIcXiJtNzRbP:-KSlqzf6HqzkdTov61qH:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/c7394fa47a5a4479501ea3dca49adf41348bb5e6/op_robot_tests/tests_files/service_keywords.py#L290)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> І це теж
</details>
done

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 499 at r8](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlaPpyFgc-ZPe04AnJ:-KSlpgl1kybD7H9xGTQB:b-7rl0kd) ([raw file](https://github.com/openprocurement/robot_tests/blob/117f73fa5997ff0645bb96fb16efac3f675c3a61/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L499)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> Зайве.
</details>
done

---

*[robot_tests_arguments/dgf_other.txt, line 4 at r18](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlkItRCQwVCN0mJSep:-KSlptVMgWHmaRFgzZ9p:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/294d27a0197aa2c5050d30ae9b12f75d112e2cec/robot_tests_arguments/dgf_other.txt#L4)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> MEAT і LOTS можна і треба викинути.
</details>
done

---

*[robot_tests_arguments/dgf_other_simple.txt, line 4 at r14](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-KSlepzhB6HGcFXxrWo9:-KSlpuZkwpWW36JO9Q5z:bb7f2mf) ([raw file](https://github.com/openprocurement/robot_tests/blob/45cb072f3cef2ed40814493ef2696d30740eea42/robot_tests_arguments/dgf_other_simple.txt#L4)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary>
> MEAT і LOTS можна і треба викинути.
</details>
done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r20, 2 of 2 files at r21, 2 of 2 files at r22, 3 of 3 files at r23, 7 of 7 files at r24.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/316#-:-KSm8jNCYkNApgmv0UeF:bnfp4nl)*

**Pull request merged**
