### PR TITLE
Add implementation of waiting for the end of the auction

### PR DESCRIPTION
**Pull request by mykhaly**
Supersedes #63.

---

This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/122)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/auction.robot, line 11 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeH6ERcRzLduMLUFnh:-KDeH6ESFHbkR-XWkh8o:2104813918) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L11)):*
Цього не треба.

---

*[op_robot_tests/tests_files/auction.robot, line 61 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeHRLAychYjBKvlFDx:-KDeHRLAychYjBKvlFDy:1938191203) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L61)):*
`Викликати для учасника` → `Run As`

---

*[op_robot_tests/tests_files/auction.robot, line 62 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeHnMr7q_YG8Rl2003:-KDeHnMr7q_YG8Rl2004:173003899) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L62)):*
`${browser}` → `${USERS.users['${viewer}'].browser}`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/122)*

**Comment by selurvedu** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/auction.robot, line 48 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeIhYYIyHXuOA9xfP6:-KDeIhYYIyHXuOA9xfP7:882246724) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L48)):*
Цього теж не треба, воно присутнє в `Test Suite Teardown`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/122)*

**Comment by mykhaly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/auction.robot, line 11 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeH6ERcRzLduMLUFnh:-KDguv4XU0yGH7sREKF7:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L11)):*
Done.

---

*[op_robot_tests/tests_files/auction.robot, line 48 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeIhYYIyHXuOA9xfP6:-KDguJTE0bT2M077uVgt:891709877) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L48)):*
Якщо це забрати, то буде відкрито два браузери, і це трохи напрягає.

---

*[op_robot_tests/tests_files/auction.robot, line 61 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeHRLAychYjBKvlFDx:-KDgutTLLuwxT6EynqJ_:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L61)):*
Done.

---

*[op_robot_tests/tests_files/auction.robot, line 62 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeHnMr7q_YG8Rl2003:-KDgutu4ZN9kCHhpb6gm:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/122)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[op_robot_tests/tests_files/auction.robot, line 48 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-KDeIhYYIyHXuOA9xfP6:-KDyBlnPeoUw7U1K4X6V:1231052311) ([raw file](https://github.com/openprocurement/robot_tests/blob/e3e7960e345194b3673f380175f7f8827526cfcc/op_robot_tests/tests_files/auction.robot#L48)):*
А, зрозумів, в наступному кроці ми отримуємо дані через брокера, а не з аукціону, і це робиться або через op_client, або через браузер.
:+1:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/openprocurement/robot_tests/122#-:-KDyC8Kbocy7HnEoFIi3:1417088721)*

**Comment by selurvedu** [comment]
> Приймаю в devel, побачимо, як себе покаже. Потім буде merge devel'у в master і цей PR автоматично закриється.

https://github.com/openprocurement/robot_tests/pull/133#issuecomment-205972173

**Pull request merged**
