### PR TITLE
Add status, diff and reflog to "Залогувати git-дані"

### PR DESCRIPTION
**Pull request by mykhaly**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/153)

### CODE REVIEW

**Comment by selurvedu** [comment]
Це ще варто обговорити...
+(in progress)
+@selurvedu

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 52 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC5guwpOEicMSP0Wk4:-KFC5gux4m4vBhXmmRBV:11364397) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L52)):*
Там може вийти досить багато output'у, щось я сумніваюсь в такій затії.

---

*[op_robot_tests/tests_files/keywords.robot, line 53 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC4yeYM0IxsB2aoVUt:-KFC4yeZoYKXSE-4RYBg:755090695) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L53)):*
А reflog для чого? Тут теж може бути довгий вихлоп.

---

*[op_robot_tests/tests_files/keywords.robot, line 57 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC50t96GeZ3cbzy_D3:-KFC50tAmGA-dmYDFYnp:770967614) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/keywords.robot#L57)):*
:hand: :no_entry_sign: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-:-KFC5G_Sp5fOntgVV8nF:-198317900)*

**Comment by selurvedu** [comment]
*[op_robot_tests/tests_files/keywords.robot, line 53 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC4yeYM0IxsB2aoVUt:-KFC6HjdiY07h75FVBR9:-76943634) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L53)):*
Та й користі від нього не особливо багато. Досі він жодного разу не був потрібен.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153)*

**Comment by mykhaly** [comment]
Окей.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 52 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC5guwpOEicMSP0Wk4:-KFJ5xNlig7a-rdF08kq:-202423368) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L52)):*
Може. Але ж це не проблемно, якщо не розкривати в log.html цей ківорд

---

*[op_robot_tests/tests_files/keywords.robot, line 53 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC4yeYM0IxsB2aoVUt:-KFJ672t8OnXMcvLSuJt:-1465923213) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L53)):*
Я це додав з розрахунку на те, що якось, одного разу, можливо, воно буде потрібно. А його не буде...
Ми ж нічого не втрачаємо тим, що додамо цей рядок.

---

*[op_robot_tests/tests_files/keywords.robot, line 57 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC50t96GeZ3cbzy_D3:-KFJ6Vd3uKV-Omyxx2od:-890665080) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/keywords.robot#L57)):*
Не знаю, звідки це взялося. Виправлю.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-:-KFJ6ZJTtf4bgA0X77HG:441332425)*

**Comment by mykhaly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 57 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC50t96GeZ3cbzy_D3:-KFd_YLvkw-GLaenOsMS:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/keywords.robot#L57)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153)*

**Comment by selurvedu** [comment]
:lgtm:
-(in progress) +ready

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 52 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC5guwpOEicMSP0Wk4:-KFjlZlA1kV5DaQigpkv:1551823114) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L52)):*
Make it so.

---

*[op_robot_tests/tests_files/keywords.robot, line 53 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-KFC4yeYM0IxsB2aoVUt:-KFjldGL89D_dz9wBKgR:1551823114) ([raw file](https://github.com/openprocurement/robot_tests/blob/010e8a122ed543f650a95a7db5bbecfb5e839a4c/op_robot_tests/tests_files/keywords.robot#L53)):*
Make it so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153#-:-KFjliuYb9KLmmwBoyWz:376551363)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/153)*

**Pull request merged**
