### PR TITLE
Chef upd

### PR DESCRIPTION
**Pull request by Leits**
Протестовано.

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/148)

### CODE REVIEW

**Comment by selurvedu** [comment]
> Caution! Не відтестована частина кваліфікації.

І що з цим робити?

**Comment by selurvedu** [comment]
+qa

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/meatTender.robot, line 159 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmTudca95xHqnFky66:-KEmTuddeI0JeaiPrcyc:189765019) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L159)):*
Поміняй теги, хай тобі @mykhaly підкаже, на які.

---

*[op_robot_tests/tests_files/meatTender.robot, line 164 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmUQ_7GmwTgnHaxZ4E:-KEmUQ_7GmwTgnHaxZ4F:-1076702) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/meatTender.robot#L164)):*
Чому забрав teardown?

---

*[op_robot_tests/tests_files/meatTender.robot, line 179 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmU5GyBnmuDrvFwMv3:-KEmU5GyBnmuDrvFwMv4:1799216584) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L179)):*
> `назви`

Хм...

---

*[op_robot_tests/tests_files/meatTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmU80TCbsd8air34j8:-KEmU80TCbsd8air34j9:1816596003) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L186)):*
Може `суми`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-:-KEmUw5gQL_n9bVmRNKx:160350294)*

**Comment by mykhaly** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/meatTender.robot, line 164 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmUQ_7GmwTgnHaxZ4E:-KEpldTYEDFN8RAxula9:-1213671084) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/meatTender.robot#L164)):*
тут не змінюються дані в цбд, тому оновлювати last_modification_date немає потреби

---

*[op_robot_tests/tests_files/meatTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmU80TCbsd8air34j8:-KEplGnyTNtbljbMHfPV:1925303219) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L186)):*
там ж нема дії додавання, щоб була якась сума. це таки значення ставки.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148)*

**Comment by Leits** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/meatTender.robot, line 159 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmTudca95xHqnFky66:-KEuW-cQa5ghq29q9Rjl:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L159)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/meatTender.robot, line 159 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmTudca95xHqnFky66:-KF54pKKctJOxnBgAzZf:-772785874) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L159)):*
Undone.

---

*[op_robot_tests/tests_files/meatTender.robot, line 164 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmUQ_7GmwTgnHaxZ4E:-KF553ZrBnm93VVL_Gm4:447307838) ([raw file](https://github.com/openprocurement/robot_tests/blob/9ef33508d606e4ab8faddd2468cdba359c9afe45/op_robot_tests/tests_files/meatTender.robot#L164)):*
Думав про зміну даних після закінчення аукціону, це вже враховано в #155.

---

*[op_robot_tests/tests_files/meatTender.robot, line 186 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmU80TCbsd8air34j8:-KF54xH2oG84nThNitot:403928163) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L186)):*
Може й так.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148)*

**Comment by selurvedu** [comment]
:lgtm:
-qa

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/meatTender.robot, line 159 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmTudca95xHqnFky66:-KF5mSWT16C24MDWiC8G:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L159)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-:-KF5mg0Cy_sfMN7Pr1Af:298221828)*

**Comment by selurvedu** [comment]
Опис PR або commit message зовсім неінформативний, дописав трохи в merge commit: 3889c59.

**Comment by selurvedu** [comment]
*[op_robot_tests/tests_files/meatTender.robot, line 179 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/148#-KEmU5GyBnmuDrvFwMv3:-KFDAG_X-4u8GV06dAZm:-1781161310) ([raw file](https://github.com/openprocurement/robot_tests/blob/5b573e402e20429be060e6a6846b6241356d7ba5/op_robot_tests/tests_files/meatTender.robot#L179)):*
"Назва" == "Коротка назва організації", але теперішній варіант годиться.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/148)*

**Pull request merged**
