### PR TITLE
belowThreshold

### PR DESCRIPTION
**Pull request by Leits**
Closes #110.

---

This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/174)

### CODE REVIEW

**Comment by mykhaly** [comment]
Коміти далі не варто зливати в один такий величезний. Краще маленькі і з толковим меседжем.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 43 unresolved discussions.

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 45 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC-lTLJBKN_ctl30Zs:-KGC-lTLJBKN_ctl30Zt:70777377) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L45)):*
добавити -> додати
не тільки у назві кейсу, але і у всіх ківордах

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 46 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC-wXBZMR8hvrkOCBX:-KGC-wXBZMR8hvrkOCBY:588379079) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L46)):*
Тег не той, здається

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 55 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0-sBi2kAh-63GDDB:-KGC0-sBi2kAh-63GDDC:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L55)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 64 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC05XlGMrwlIHGDu_i:-KGC05XlGMrwlIHGDu_j:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L64)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 74 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC07nfIkvYD3iG-WLk:-KGC07nfIkvYD3iG-WLl:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L74)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 100 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0Ejz0S5cs4VQkilT:-KGC0Ek--kDN86-rDk7A:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L100)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 105 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0H08Z8FcjB1I6J5K:-KGC0H08Z8FcjB1I6J5L:619773070) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L105)):*
Треба змінити хардкод на якісь фейкові дані.

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 109 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0NGBiT2lo8IYmTBO:-KGC0NGBiT2lo8IYmTBP:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L109)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 114 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0ObTRKcWmGn8zx6H:-KGC0ObTRKcWmGn8zx6I:561005196) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L114)):*
Хардкод

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 129 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0Ttip6MrDaLn2hbv:-KGC0Ttip6MrDaLn2hbw:-1566135094) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L129)):*
Або всюди `питання`, або всюди `запитання`

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 180 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0lgLJd7nUcu7k-X-:-KGC0lgLJd7nUcu7k-X0:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L180)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 193 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0ng_kGjHCHZGWSHh:-KGC0ng_kGjHCHZGWSHi:561005196) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L193)):*
Хардкод

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 201 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0rzAGdC2yMh6njyi:-KGC0rzAGdC2yMh6njyj:561005196) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L201)):*
Хардкод

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 212 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC11_KVo5DmBjjNhn6:-KGC11_KVo5DmBjjNhn7:-1734991211) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L212)):*
`цінової` або всюди писати, або всюди не писати

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 221 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC19gk2iZWrT-gPgMJ:-KGC19gk2iZWrT-gPgMK:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L221)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 228 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1BaxCy6KQPnQjska:-KGC1BaxCy6KQPnQjskb:161356571) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L228)):*
Тег

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 10 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1JCVYhEd4EPNMolS:-KGC1JCVYhEd4EPNMolT:-783321641) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L10)):*
Було б краще, щоб всі ківорди писалися за одним принципом. Або всюди використовувати інфінітив дієслова, або наказовий спосіб дієслова. Бо тут `Підготовка`, а далі `Адаптувати`.
Я - за наказовий спосіб

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 15 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1qTfFpd9B3d-Cg9u:-KGC1qTgtBbM43mVuL1P:1269074763) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L15)):*
Можна всі логи оці позабирати. Коли вони будуть потрібні - використовувати `-L TRACE:INFO`

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 30 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1xtN6nYmuIUtpIli:-KGC1xtN6nYmuIUtpIlj:343159422) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L30)):*
Те саме стосовно логів, що і вище

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 33 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC21a_mT9njbtmGzoQ:-KGC21a_mT9njbtmGzoR:166172853) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L33)):*
Добавити -> додати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 34 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC24k1ny-WD-U3IW9K:-KGC24k1ny-WD-U3IW9L:-935818939) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L34)):*
Підготовка -> підготувати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 51 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2DNeIptEDJCXDFX5:-KGC2DNeIptEDJCXDFX6:-203584724) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L51)):*
По всьому тест сьюту пройтися і видалити непотрібні три і більше пробіли підряд

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 55 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2NZyNExQmcQU1qVo:-KGC2NZyNExQmcQU1qVp:1678854525) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L55)):*
Описував проблему вище

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 57 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2Qr2iPqZqu9Ew_lK:-KGC2Qr2iPqZqu9Ew_lL:1678854525) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L57)):*
Описував проблему вище

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 70 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2VTIj-mM6Yp4Ixr7:-KGC2VTIj-mM6Yp4Ixr8:-2102508974) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L70)):*
Створення -> створити

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 71 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2YR2tm0AXle7uPzn:-KGC2YR2tm0AXle7uPzo:1678854525) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L71)):*
Описував проблему вище

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 84 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2iz7DR9yDwq8qHpi:-KGC2iz7DR9yDwq8qHpj:1575121525) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L84)):*
Гарно придумав.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 93 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2t45mtWBKM1PhHWL:-KGC2t45mtWBKM1PhHWM:-1145346741) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L93)):*
Тоді вже по аналогії перейменувати в `Відображення ${filed} першого лоту для користувача`

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 100 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC34mVRMeAFGM3U-wm:-KGC34mVRMeAFGM3U-wn:101522390) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L100)):*
Оце добре.
Але чи можна було би `першого` замінити на ${lot_number}?
Тоді наступний рядок виглядав би отак:
`${lot_id}=  get_id_from_object  ${USERS.users['${tender_owner}'].initial_data.data.lots[${lot_number}]}`

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 108 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC3z4NeLqNZ-5p3D6o:-KGC3z4NeLqNZ-5p3D6p:650440346) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L108)):*
Чи реально замість `тендер` зробити `${question_type}`?
І в залежності від тої змінної викликати певне ключове слово з op_client.robot

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 110 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC3YqV8LYrpH_gPoEE:-KGC3YqV8LYrpH_gPoEF:-935818939) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L110)):*
Підготовка -> підготувати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 123 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC3qJyywuTcQ-7fMOA:-KGC3qJyywuTcQ-7fMOB:-935818939) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L123)):*
Підготовка -> підготувати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 135 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC3u1VbcL65HHi-nrx:-KGC3u1VbcL65HHi-nry:-935818939) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L135)):*
Підготовка -> підготувати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 145 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC4On_aLJNuYL5ks9N:-KGC4On_aLJNuYL5ks9O:-935818939) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L145)):*
Підготовка -> підготувати

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 146 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC4S6CTrdf6yAYUFCn:-KGC4S6CTrdf6yAYUFCo:-1903844973) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L146)):*
Варто, мабуть, всюди записувати аргументи в багато рядків.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 159 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC4cN8f29VHA1OMZqz:-KGC4cN8f29VHA1OMZr-:-315949484) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L159)):*
Аналогічно
Чи реально замість `тендер` зробити `${bid_type}`?
І в залежності від тої змінної викликати певне ключове слово з op_client.robot

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 206 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC523fe0GlmhXV_CyK:-KGC523fe0GlmhXV_CyL:1120724165) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L206)):*
Видалити?

---

*[op_robot_tests/tests_files/initial_data.py, line 287 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5CY2Wo5-WPhFDXdF:-KGC5CY2Wo5-WPhFDXdG:1337086256) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/initial_data.py#L287)):*
relation -> related, аргумент залишити як є

---

*[op_robot_tests/tests_files/initial_data.py, line 462 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5PpzuzSmQw9wRNQr:-KGC5PpzuzSmQw9wRNQs:-89121859) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/initial_data.py#L462)):*
Чому `list()`, а не `[ ]`?

---

*[op_robot_tests/tests_files/keywords.robot, line 241 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5d6m2_ruFsf2YdpF:-KGC5d6m2_ruFsf2YdpG:-1800576966) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/keywords.robot#L241)):*
Тут не supplier_data, але це, здається, десь вже виправлено.

---

*[op_robot_tests/tests_files/service_keywords.py, line 306 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5lu6aiBXIVls8aXk:-KGC5lu7Ei23U77bqLrM:2015385826) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/service_keywords.py#L306)):*
посортувати if-ки по-алфавіту.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 118 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5x8Aqih_jg2a0xTj:-KGC5x8Aqih_jg2a0xTk:1959259750) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L118)):*
Що цей ${lot_id} дає?

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 349 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC6AVtwsmax3mfRhyV:-KGC6AVtwsmax3mfRhyW:433446655) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L349)):*
Переіменувати в `Задати питання на тендер`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGC6JBp3vPEljmvEB8l:-1574387638)*

**Comment by selurvedu** [comment]
+1.

---

Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 43 unresolved discussions.

---

*[op_robot_tests/tests_files/initial_data.py, line 287 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5CY2Wo5-WPhFDXdF:-KGDe-NadK0iwQOS0_b4:676269983) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/initial_data.py#L287)):*
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGDe5gJ9Q4Qmb4Sr8fb:160348259)*

**Comment by Leits** [comment]
Маленькі не вийде.

---

Review status: all files reviewed at latest revision, 43 unresolved discussions.

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 45 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC-lTLJBKN_ctl30Zs:-KGEBLVi5RqFZLcxXYzv:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L45)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 129 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0Ttip6MrDaLn2hbv:-KGEBV3vnPTzK4lZOVg7:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L129)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 15 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1qTfFpd9B3d-Cg9u:-KGEBYDoEyLCwZOV4QAU:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L15)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 33 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC21a_mT9njbtmGzoQ:-KGEB_MBMY7D7-3Tash9:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L33)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 206 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC523fe0GlmhXV_CyK:-KGECnsu5Y9F3eqzJ_RE:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L206)):*
Done.

---

*[op_robot_tests/tests_files/initial_data.py, line 287 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5CY2Wo5-WPhFDXdF:-KGEAVO5HblkUlBa1mI8:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/initial_data.py#L287)):*
Done.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 118 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC5x8Aqih_jg2a0xTj:-KGEAJiZ6cnsLPQGlyNb:-1716613308) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L118)):*
Для нас нічого, майданчу дає ідентифікатор лоту, з якого видаляти предмет.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 349 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC6AVtwsmax3mfRhyV:-KGEAIiWrWomV82YGuMX:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L349)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGEAXrCvMUGqfmfjUIG:305931360)*

**Comment by mykhaly** [comment]
Чому?

---

Review status: 0 of 7 files reviewed at latest revision, 37 unresolved discussions.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 15 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1qTfFpd9B3d-Cg9u:-KGGVGhmTeNCKtmz1akI:2024583732) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L15)):*
Тепер --loglevel trace:info є за замовчуванням в команді запуску

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGGV27esAANmjWPPE0b:449770332)*

**Comment by Leits** [comment]
Занадто неоднорідні зміни.

---

Review status: 0 of 7 files reviewed at latest revision, 36 unresolved discussions.

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 105 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC0H08Z8FcjB1I6J5K:-KGH08FOBzuhuQC_KFUc:-391929186) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L105)):*
@selurvedu cast!

---

*[op_robot_tests/tests_files/belowThreshold.robot, line 212 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC11_KVo5DmBjjNhn6:-KGH0RkzTUDkq5O36xqF:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold.robot#L212)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 30 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC1xtN6nYmuIUtpIli:-KGH0Uji8vNAKvpsQ4Ng:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L30)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 51 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2DNeIptEDJCXDFX5:-KGH0WTnmCQpu71JhV8Q:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L51)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 70 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2VTIj-mM6Yp4Ixr7:-KGH0ZyUx5-xrLjlalqM:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L70)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 93 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC2t45mtWBKM1PhHWL:-KGH0csG8meC8flrsEQv:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L93)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 100 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC34mVRMeAFGM3U-wm:-KGH0dfQPT4kd9YwqYvi:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L100)):*
Done.

---

*[op_robot_tests/tests_files/belowThreshold_keywords.robot, line 108 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-KGC3z4NeLqNZ-5p3D6o:-KGH0fM5GO1yzZemVCHY:1915567441) ([raw file](https://github.com/openprocurement/robot_tests/blob/1950fee0f9eec9db36dea22006a44d172caece67/op_robot_tests/tests_files/belowThreshold_keywords.robot#L108)):*
Є відмінність у викликах.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGH0sy0JLHS0D_zew4A:414893851)*

**Comment by mykhaly** [comment]
Не ок це. Процедуру ж ти створював по кроках, так і робив би коміти. 
1)Add tender creation to belowThreshold.robot
2)Add tender searching to belowThreshold.robot
...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGH7GQnyVGogbtZ_7Jt:-725222397)*

**Comment by Leits** [comment]
Я не створював її по кроках, я взяв існуючу і її перероблював, на ходу змімнюючі і попередні куски через баги, які вилізали потім. Тому я міг відправити сотню комітів, які змінюють один одного, або один великий, як факт створеного каркасу процедури. Немає сенсу віддавати комітом те, що точно потім зміниться.

---

Review status: 0 of 10 files reviewed at latest revision, 32 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/174#-:-KGH9TfzJy0KbI90A9tD:1602812501)*

**Pull request merged**
