### PR TITLE
Add tests for integration with MOZ

### PR DESCRIPTION
**Pull request by OrysiaDrabych**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/696)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 20 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NuayRJtz1vi6QGiT7:-L1NuayRJtz1vi6QGiT8:b-7owc2i) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/base_keywords.robot#L20)):*
> ${moz_integration}

I think this variable's name should be in upper case, just like the others.

---

*[op_robot_tests/tests_files/initial_data.py, line 154 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NvMHTqO2fdrzA8OiP:-L1NvMHTqO2fdrzA8OiQ:b-973uhv) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/initial_data.py#L154)):*
> cpv_group = fake.cpv('336')[:3]

This line can be safely reduced to `cpv_group = 336`. The CPV group that is going to be used is known in advance, so there is no need to pick a random CPV and slice a group prefix out of it.

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 104 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NtsG-x0jzfzACXI05:-L1NtsG09qedveFFwOD0:bwa23vq) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/op_faker/op_faker.py#L104)):*
> cpv_id

IMHO, cpv_group is better (also, we've already used this name in initial_data.py and op_faker.py).

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 106 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1Ntx2dsSG57sq04ivQ:-L1Ntx2dsSG57sq04ivR:b-5m1mum) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/op_faker/op_faker.py#L106)):*
> ```Python
>     def cpv(self, cpv_id=None):
>         if cpv_id:
>             cpvs_moz = []
> ```

Since this function can work with any CPV group, this list is not restricted to the CPV group 336 and has nothing to do with MOZ. Give it a better name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/696)*

**Comment by OrysiaDrabych** [comment]
Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/base_keywords.robot, line 20 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NuayRJtz1vi6QGiT7:-L1Y4QMzZbiA3dHcUriG:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/base_keywords.robot#L20)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

> ${moz_integration}

I think this variable's name should be in upper case, just like the others.
</blockquote></details>

Done.

---

*[op_robot_tests/tests_files/initial_data.py, line 154 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NvMHTqO2fdrzA8OiP:-L1Y4R1vAj44qfL9iiXG:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/initial_data.py#L154)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

> cpv_group = fake.cpv('336')[:3]

This line can be safely reduced to `cpv_group = 336`. The CPV group that is going to be used is known in advance, so there is no need to pick a random CPV and slice a group prefix out of it.
</blockquote></details>

Done.

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 104 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1NtsG-x0jzfzACXI05:-L1Y4VXhxJGMysMTQrYa:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/op_faker/op_faker.py#L104)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

> cpv_id

IMHO, cpv_group is better (also, we've already used this name in initial_data.py and op_faker.py).
</blockquote></details>

Done.

---

*[op_robot_tests/tests_files/op_faker/op_faker.py, line 106 at r1](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-L1Ntx2dsSG57sq04ivQ:-L1Y4WEdJ0tZhsMsCNV0:b-896fix) ([raw file](https://github.com/openprocurement/robot_tests/blob/311e1d1d24b424043a23044d9178eb1c10b69d52/op_robot_tests/tests_files/op_faker/op_faker.py#L106)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Since this function can work with any CPV group, this list is not restricted to the CPV group 336 and has nothing to do with MOZ. Give it a better name.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/696)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/696#-:-L1YH0lPSFN-8FE2lhek:bnfp4nl)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/696)*

**Pull request merged**
