### PR TITLE
add availableLanguage only if procurementMethodType not competitiveDialogueEU

### PR DESCRIPTION
**Pull request by Krokop**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/247)

### CODE REVIEW

**Comment by mykhaly** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/247)*

**Comment by mykhaly** [comment]
Це готовий пул-реквест? Чи будуть ще коміти?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/247#-:-KLp8CgJxPdl7QeJFzsA:447877233)*

**Comment by Krokop** [comment]
Готовий.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/247#-:-KLp8WTtYPCU2xgoz1t6:-1488123801)*

**Comment by mykhaly** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/247#-:-KLp9008zBOGcVHGOdIt:1417088721)*

**Pull request merged**
