### PR TITLE
Compare coordinates

### PR DESCRIPTION
**Pull request by Leits**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/154)

### CODE REVIEW

**Comment by selurvedu** [comment]
+qa

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 371 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCGpHfLdyoM3Z1Kwmc:-KFCGpHfLdyoM3Z1Kwmd:-1532466719) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L371)):*
Здається, це не arcdegree, а decimal degree (я не впевнений, перевір).

---

*[op_robot_tests/tests_files/keywords.robot, line 375 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCGxyZ51c4dHfazPPe:-KFCGxyZ51c4dHfazPPf:1042962601) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L375)):*
> dates

Зайве.

---

*[op_robot_tests/tests_files/keywords.robot, line 377 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC6pqKcsjLGPR1DAJb:-KFC6pqLILTikxngL76D:1637973456) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L377)):*
> 0.01

https://en.wikipedia.org/wiki/Decimal_degrees
IMHO: Якось малувато, але поки що не міняй...

---

*[op_robot_tests/tests_files/keywords.robot, line 383 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCBipKN67lPl-Yz5JB:-KFCBipKN67lPl-Yz5JC:856164632) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L383)):*
> `are not equal`

Краще `differ`.

---

*[op_robot_tests/tests_files/keywords.robot, line 402 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCHU738uUdpC4aoKe4:-KFCHU74lCuCAfYwygU3:-1534891055) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L402)):*
+1 порожній рядок.

---

*[op_robot_tests/tests_files/keywords.robot, line 407 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCHct9gMQL_Et5eCc7:-KFCHctA9gtxV5vQj3Yw:-1701529887) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L407)):*
Пробував з `IN ENUMERATE`? Якщо спрацює, то зміни і в попередньому ківорді.

---

*[op_robot_tests/tests_files/service_keywords.py, line 89 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC7yXgPgqGrA55kreg:-KFC7yXh-7rPWO8I9YCf:-1895970885) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/service_keywords.py#L89)):*
Не варто перетворювати в `float`. `int` від `float`’у відніметься без проблем (і навпаки), а для всього іншого має кидатись помилка. Краще перенеси `num_types` з `compute_intrs` на рівень вище, щоб він був доступний і звідси (наприклад, розмісти його після імпортів), і потім напиши тут наступне:
```python
for key, value in {'left': left, 'right': right}.iteritems():
    if not isinstance(value, num_types):
        raise TypeError("Invalid type for coordinate '{0}'. "
                        "Expected one of {1}, got {2}".format(
                            key, str(num_types), str(type(value))))
```

Крім цього поміняй `coord1` і `coord2` на `left` і `right`, щоб співпадало з назвами змінних в `Порівняти координати`. Так легше буде зрозуміти, на яку змінну дивитись в лоґу.

---

*[op_robot_tests/tests_files/service_keywords.py, line 91 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC8NTqLJj4QgFV5MgY:-KFC8NTr2NXSiWSgVThW:-1983166539) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/service_keywords.py#L91)):*
А дужки для чого?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-:-KFCIPaKWY7QhrV00MLe:160350294)*

**Comment by selurvedu** [comment]
*[op_robot_tests/tests_files/keywords.robot, line 383 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCBipKN67lPl-Yz5JB:-KFCIkRkNIhSc4rJcXCa:-1155585408) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L383)):*
І в порівнянні дат теж треба поміняти.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by Leits** [comment]
Review status: 3 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 371 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCGpHfLdyoM3Z1Kwmc:-KFEd-EMYeAhB7T2j7Zr:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L371)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 375 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCGxyZ51c4dHfazPPe:-KFEfQXD2_0VNzc1KR-q:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L375)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 383 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCBipKN67lPl-Yz5JB:-KFEfP8eVA0dfA84liRO:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L383)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 402 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCHU738uUdpC4aoKe4:-KFEfOX6RlOkuL0yYLpx:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L402)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 407 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFCHct9gMQL_Et5eCc7:-KFEjCaFqwlGDvg28p_8:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L407)):*
Done.

---

*[op_robot_tests/tests_files/service_keywords.py, line 89 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC7yXgPgqGrA55kreg:-KFEccQgQH8O75JUk5Kx:-835615523) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/service_keywords.py#L89)):*
А якщо майданчик поверне той же float у стрічці? Або відправить його стрічкою у цбд?

---

*[op_robot_tests/tests_files/service_keywords.py, line 91 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC8NTqLJj4QgFV5MgY:-KFEfInXe7PAzI1ppOow:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/service_keywords.py#L91)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by selurvedu** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/service_keywords.py, line 89 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC7yXgPgqGrA55kreg:-KFFBC7I1PIEfPzh_8Oy:1811172760) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/service_keywords.py#L89)):*
Ківорд майданчика має дати нам float/int/long.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by selurvedu** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by Leits** [comment]
Переписав на порівняння координат замість порівняння float-ів.

**Comment by myroslav** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 357 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhJfFthRi0SUBEWsOy:-KFhJfFvEuDM0PBZ5tC8:284012211) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L357)):*
координати доставки

---

*[op_robot_tests/tests_files/keywords.robot, line 403 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhJjveFFja_0FZR-LI:-KFhJjvfkNwhWSO8piys:284012211) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L403)):*
координати доставки

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by Leits** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 357 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhJfFthRi0SUBEWsOy:-KFhPFSwNItODAi_tpj4:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L357)):*
Done.

---

*[op_robot_tests/tests_files/keywords.robot, line 403 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhJjveFFja_0FZR-LI:-KFhPHynWZKkVhcElHaE:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L403)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by myroslav** [comment]
Reviewed 4 of 4 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/service_keywords.py, line 95 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhgEws175mc_4ASjco:-KFhgEws175mc_4ASjcp:1355225449) ([raw file](https://github.com/openprocurement/robot_tests/blob/ec33bb32333e8578e840bc8ff40d29f4ce1ba6fc/op_robot_tests/tests_files/service_keywords.py#L95)):*
є сенс використати бібліотеку?
from haversine import haversine

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by selurvedu** [comment]
@Leits, this looks good, this looks good!
@myroslav, thanks.

---

Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 425 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFqt9_oMiAJjoyZ-v5t:-KFqt9_oMiAJjoyZ-v5u:-1699130349) ([raw file](https://github.com/openprocurement/robot_tests/blob/53a29ce3d7614b423c2c5d11f9496df716160d86/op_robot_tests/tests_files/keywords.robot#L425)):*
Лапки не потрібні.
```robotramework
$ bin/rfshell 
> Should Be True  ${False}  msg="Foo Bar ${True}"
< keyword: Should Be True  ${False}  msg="Foo Bar ${True}"
! "Foo Bar True"
> Should Be True  ${False}  msg=Foo Bar ${True}
< keyword: Should Be True  ${False}  msg=Foo Bar ${True}
! Foo Bar True
```
Перед і після ’!=’ встав пробіли.

---

*[op_robot_tests/tests_files/service_keywords.py, line 95 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhgEws175mc_4ASjco:-KFquCmm8K2-knaezvJT:-403577979) ([raw file](https://github.com/openprocurement/robot_tests/blob/ec33bb32333e8578e840bc8ff40d29f4ce1ba6fc/op_robot_tests/tests_files/service_keywords.py#L95)):*
:heavy_plus_sign:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-:-KFqvZfAtoN2yJIHxUH7:1274736279)*

**Comment by Leits** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 425 \[r4\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFqt9_oMiAJjoyZ-v5t:-KFt2fEI1ZZjEi8E6lNO:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/53a29ce3d7614b423c2c5d11f9496df716160d86/op_robot_tests/tests_files/keywords.robot#L425)):*
Done.

---

*[op_robot_tests/tests_files/service_keywords.py, line 95 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFhgEws175mc_4ASjco:-KFt2hJCn9QsyQD7T3FG:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/ec33bb32333e8578e840bc8ff40d29f4ce1ba6fc/op_robot_tests/tests_files/service_keywords.py#L95)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by mykhaly** [comment]
Reviewed 6 of 6 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by mykhaly** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 377 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC6pqKcsjLGPR1DAJb:-KFtBV2S022nrJSLSYqA:348467447) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L377)):*
Тепер це 0.1 - 100 метрів. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154)*

**Comment by mykhaly** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-:-KFtCFWlwpnwVDDP30jG:1417088721)*

**Comment by selurvedu** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[op_robot_tests/tests_files/keywords.robot, line 377 \[r1\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KFC6pqKcsjLGPR1DAJb:-KG7kQsPOOia0_JeN7un:676269983) ([raw file](https://github.com/openprocurement/robot_tests/blob/19d2e6ea6e8f7561f96d64f7bf9be922b2c5677e/op_robot_tests/tests_files/keywords.robot#L377)):*
:+1:

---

*[op_robot_tests/tests_files/service_keywords.py, line 128 \[r7\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KG7jjslK-Hz3KdErB_P:-KG7jjsmWzz7YZe8U2I3:-1685239905) ([raw file](https://github.com/openprocurement/robot_tests/blob/640ccf20809438b92bec28fe67dda854e56bf690/op_robot_tests/tests_files/service_keywords.py#L128)):*
dates?

---

*[op_robot_tests/tests_files/service_keywords.py, line 130 \[r7\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KG7jmHbB3AHtnsjssI6:-KG7jmHcNwJF5UVqc-Le:-167906728) ([raw file](https://github.com/openprocurement/robot_tests/blob/640ccf20809438b92bec28fe67dda854e56bf690/op_robot_tests/tests_files/service_keywords.py#L130)):*
Long live copypaste!

---

*[op_robot_tests/tests_files/service_keywords.py, line 145 \[r7\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-KG7jwslbs_8BD21yn6D:-KG7jwslbs_8BD21yn6E:1249741087) ([raw file](https://github.com/openprocurement/robot_tests/blob/640ccf20809438b92bec28fe67dda854e56bf690/op_robot_tests/tests_files/service_keywords.py#L145)):*
:+1: :+1: :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/154#-:-KG7kV6tlaJ50gmuPqzJ:-1168659251)*

**Pull request merged**
