### PR TITLE
Lot auction, qualification and contract

### PR DESCRIPTION
**Pull request by Leits**
Перенесення у гілку devel [#147](https://github.com/openprocurement/robot_tests/pull/147)
_____

This change is [Reviewable](https://reviewable.io/reviews/openprocurement/robot_tests/160)

### CODE REVIEW

**Comment by selurvedu** [comment]
Reviewed 3 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, 5 of 6 files at r5.
Review status: 13 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 179 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKDrHBxE9DYgJUks_x:-KFKDrHCp2ysbWlfp4ex:-146541708) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/keywords.robot#L179)):*
Додай ініціалізацію `${lot_index}` нулем якщо вона не існує (через `${lot_index}=  Get Variable Value  ${lot_index}  0`).

---

*[op_robot_tests/tests_files/qualification.robot, line 31 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKFYIlSxIqxIk6trqw:-KFKFYIlSxIqxIk6trqx:-481275147) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/qualification.robot#L31)):*
В безлотовому статус буде `active.qualification`, а не `active`.

---

*[op_robot_tests/tests_files/brokers/openprocurement_client.robot, line 242 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKGRHlskqg7wcdLDZU:-KFKGRHlskqg7wcdLDZV:2094510496) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/brokers/openprocurement_client.robot#L242)):*
Костиль, який треба викинути в єдиній допороговій.

---

*[op_robot_tests/tests_files/data/users.yaml, line 13 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKCNVacwp8qW0Mwvnm:-KFKCNVbEaFPc0AqY6LF:-469080666) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/data/users.yaml#L13)):*
:thumbsdown:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160)*

**Comment by selurvedu** [comment]
-(in progress) +qa

---

Reviewed 1 of 6 files at r5, 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 179 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKDrHBxE9DYgJUks_x:-KFkES-ZV63W8hLEuoV6:-932001194) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/keywords.robot#L179)):*
1) А чи потрібен тут тепер `run keyword and ignore error`?
2) Виник сумнів, як воно себе буде поводити на безлотових. Зараз нам не цікаві безлотові, але можливо до цього треба буде повернутись.

---

*[op_robot_tests/tests_files/keywords.robot, line 179 \[r6\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFkDyQMvSznEuE9oDcy:-KFkDyQNJARaxEC_TfCX:727232330) ([raw file](https://github.com/openprocurement/robot_tests/blob/51198e0395d39ecc58d98ebe9b03d39c2cd6d0f9/op_robot_tests/tests_files/keywords.robot#L179)):*
Краще на `suite` заміни.

---

*[op_robot_tests/tests_files/qualification.robot, line 31 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKFYIlSxIqxIk6trqw:-KFkEuu3R0hTUjXhR0t6:1183223620) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/qualification.robot#L31)):*
Done. Непогано придумав.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-:-KFkFm77Bq2RMjeLQCc-:-1362322788)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 179 \[r5\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFKDrHBxE9DYgJUks_x:-KFcsZLkcTP-1nfFqT5K:994426435) ([raw file](https://github.com/openprocurement/robot_tests/blob/a4dcd5014b7f38e44d1e27d5e716fa3f83ffa350/op_robot_tests/tests_files/keywords.robot#L179)):*
Потрібен. У цьому і суть, якщо лотовий, то LOT_ID запишеться із артефакту, якщо існує відповідний лот. Якщо ж ні - Empty. Усе працює. Тестував.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160)*

**Comment by Leits** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 179 \[r6\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFkDyQMvSznEuE9oDcy:-KFn3q4bOrdpct2V-kt0:-499146009) ([raw file](https://github.com/openprocurement/robot_tests/blob/51198e0395d39ecc58d98ebe9b03d39c2cd6d0f9/op_robot_tests/tests_files/keywords.robot#L179)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160)*

**Comment by selurvedu** [comment]
Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 579 \[r6\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFocokasHWKsaoqN5qB:-KFocokbxNQ1vh5UhqNH:-987630496) ([raw file](https://github.com/openprocurement/robot_tests/blob/51198e0395d39ecc58d98ebe9b03d39c2cd6d0f9/op_robot_tests/tests_files/keywords.robot#L579)):*
А це звідки взялось/куди ділось?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160)*

**Comment by Leits** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[op_robot_tests/tests_files/keywords.robot, line 579 \[r6\]](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-KFocokasHWKsaoqN5qB:-KFohrnGq8xnrPG1OvSz:-543284927) ([raw file](https://github.com/openprocurement/robot_tests/blob/51198e0395d39ecc58d98ebe9b03d39c2cd6d0f9/op_robot_tests/tests_files/keywords.robot#L579)):*
Після закінчення цього періоду можна підписати контракт. Тобто це для contract тесту. Посунулось нижче, на 613 рядок, бо аукціон передує цій дії.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160)*

**Comment by selurvedu** [comment]
:lgtm:
-qa +ready

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/robot_tests/160#-:-KFoikvlcV-yd0DPmJ2y:-2026326284)*

**Pull request merged**
